-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_THOUSAND_NEEDLES.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_THOUSAND_NEEDLES",
    name = "Thousand Needles 25-35 (Horde)",
    version = 1,
    faction = "Horde",
    minLevel = 25,
    maxLevel = 35,
    map = 1441,
    zone = "Thousand Needles",
    next = "GEN_HORDE_DESOLACE",
    author = "ForeverGuide route generator",
    notes = "Auto-generated from the quest database: 24 quests, 71 steps, model reaches level 32. Not a speedrun route - a sensible order; the engine adapts as you play.",
    steps = {
        { type = "ACCEPT", quest = 4841, questName = "Pacify the Centaur", npc = 10537, npcName = "Cliffwatcher Longhorn", map = 1441, zone = "Thousand Needles", x = 45.7, y = 50.7 }, -- 1
        { type = "ACCEPT", quest = 4821, questName = "Alien Egg", npc = 10539, npcName = "Hagar Lightninghoof", map = 1441, zone = "Thousand Needles", x = 44.6, y = 50.3 }, -- 2
        { type = "ACCEPT", quest = 5147, questName = "Wanted - Arnak Grimtotem", map = 1441, zone = "Thousand Needles", x = 46, y = 50.9 }, -- 3
        { type = "ACCEPT", quest = 4767, questName = "Wind Rider", npc = 10377, npcName = "Elu", map = 1441, zone = "Thousand Needles", x = 44.9, y = 48.9 }, -- 4
        { type = "COLLECT", quest = 4821, questName = "Alien Egg", target = "Alien Egg", map = 1441, zone = "Thousand Needles", x = 52.3, y = 55.3, near = true }, -- 5
        { type = "KILL", quest = 4841, questName = "Pacify the Centaur", npc = 4094, target = "Galak Scout / Galak Wrangler", map = 1441, zone = "Thousand Needles", x = 45.5, y = 43.5, near = true }, -- 6
        { type = "KILL", quest = 4841, questName = "Pacify the Centaur", npc = 4096, target = "Galak Windchaser", map = 1441, zone = "Thousand Needles", x = 44.5, y = 41.4, near = true }, -- 7
        { type = "KILL", quest = 5147, questName = "Wanted - Arnak Grimtotem", npc = 10896, target = "Arnak Grimtotem", map = 1441, zone = "Thousand Needles", x = 38.1, y = 26.9, note = "loot Arnak's Hoof" }, -- 8
        { type = "ACCEPT", quest = 4904, questName = "Free at Last", npc = 10646, npcName = "Lakota Windsong", map = 1441, zone = "Thousand Needles", x = 38, y = 26.5 }, -- 9
        { type = "COMPLETE", quest = 4904, questName = "Free at Last", target = "Escort Lakota Windsong from the Darkcloud Pinnacle.", map = 1441, zone = "Thousand Needles", x = 30.9, y = 37.1, note = "Escort Lakota Windsong from the Darkcloud Pinnacle." }, -- 10
        { type = "ACCEPT", quest = 5151, questName = "Hypercapacitor Gizmo", npc = 10941, npcName = "Wizlo Bearingshiner", map = 1441, zone = "Thousand Needles", x = 21.4, y = 32.6, optional = true, note = "elite target - bring a group (optional)" }, -- 11
        { type = "COLLECT", quest = 4767, questName = "Wind Rider", target = "Highperch Wyvern Egg", map = 1441, zone = "Thousand Needles", x = 17.2, y = 40.8, near = true }, -- 12
        { type = "ACCEPT", quest = 4770, questName = "Homeward Bound", npc = 10427, npcName = "Pao'ka Swiftmountain", map = 1441, zone = "Thousand Needles", x = 17.9, y = 40.6 }, -- 13
        { type = "COMPLETE", quest = 4770, questName = "Homeward Bound", target = "Escort Pao'ka from Highperch", map = 1441, zone = "Thousand Needles", x = 15.2, y = 32.6, note = "Escort Pao'ka from Highperch" }, -- 14
        { type = "KILL", quest = 5151, questName = "Hypercapacitor Gizmo", npc = 10992, target = "Enraged Panther", map = 1441, zone = "Thousand Needles", x = 22.8, y = 24.6, optional = true, note = "ELITE - loot Hypercapacitor Gizmo (group quest, optional)" }, -- 15
        { type = "TURNIN", quest = 4770, questName = "Homeward Bound", npc = 10428, npcName = "Motega Firemane", map = 1441, zone = "Thousand Needles", x = 21.5, y = 32.4 }, -- 16
        { type = "TURNIN", quest = 5151, questName = "Hypercapacitor Gizmo", npc = 10941, npcName = "Wizlo Bearingshiner", map = 1441, zone = "Thousand Needles", x = 21.4, y = 32.6, optional = true }, -- 17
        { type = "TURNIN", quest = 4821, questName = "Alien Egg", npc = 10539, npcName = "Hagar Lightninghoof", map = 1441, zone = "Thousand Needles", x = 44.6, y = 50.3 }, -- 18
        { type = "ACCEPT", quest = 4865, questName = "Serpent Wild", npc = 10539, npcName = "Hagar Lightninghoof", map = 1441, zone = "Thousand Needles", x = 44.6, y = 50.3 }, -- 19
        { type = "TURNIN", quest = 4841, questName = "Pacify the Centaur", npc = 10537, npcName = "Cliffwatcher Longhorn", map = 1441, zone = "Thousand Needles", x = 45.7, y = 50.7 }, -- 20
        { type = "TURNIN", quest = 5147, questName = "Wanted - Arnak Grimtotem", npc = 10537, npcName = "Cliffwatcher Longhorn", map = 1441, zone = "Thousand Needles", x = 45.7, y = 50.7 }, -- 21
        { type = "TURNIN", quest = 4767, questName = "Wind Rider", npc = 10377, npcName = "Elu", map = 1441, zone = "Thousand Needles", x = 44.9, y = 48.9 }, -- 22
        { type = "TURNIN", quest = 4904, questName = "Free at Last", npc = 10645, npcName = "Thalia Amberhide", map = 1441, zone = "Thousand Needles", x = 46, y = 51.6 }, -- 23
        { type = "ACCEPT", quest = 5064, questName = "Grimtotem Spying", npc = 10537, npcName = "Cliffwatcher Longhorn", map = 1441, zone = "Thousand Needles", x = 45.7, y = 50.7 }, -- 24
        { type = "COLLECT", quest = 5064, questName = "Grimtotem Spying", target = "Secret Note #1 / Secret Note #2 / Secret Note #3", map = 1441, zone = "Thousand Needles", x = 39.3, y = 41.5, near = true }, -- 25
        { type = "TURNIN", quest = 5064, questName = "Grimtotem Spying", npc = 10537, npcName = "Cliffwatcher Longhorn", map = 1441, zone = "Thousand Needles", x = 45.7, y = 50.7 }, -- 26
        { type = "ACCEPT", quest = 1149, questName = "Test of Faith", npc = 2986, npcName = "Dorn Plainstalker", map = 1441, zone = "Thousand Needles", x = 54, y = 41.5 }, -- 27
        { type = "COMPLETE", quest = 1149, questName = "Test of Faith", target = "If you have faith, leap from the planks overlooking Thousand Needles.", map = 1441, zone = "Thousand Needles", x = 26.4, y = 32.9, note = "If you have faith, leap from the planks overlooking Thousand Needles." }, -- 28
        { type = "TURNIN", quest = 4865, questName = "Serpent Wild", npc = 10428, npcName = "Motega Firemane", map = 1441, zone = "Thousand Needles", x = 21.5, y = 32.4 }, -- 29
        { type = "ACCEPT", quest = 5062, questName = "Sacred Fire", npc = 10428, npcName = "Motega Firemane", map = 1441, zone = "Thousand Needles", x = 21.5, y = 32.4 }, -- 30
        { type = "COLLECT", quest = 5062, questName = "Sacred Fire", target = "Incendia Agave", map = 1441, zone = "Thousand Needles", x = 33.3, y = 33.5, near = true }, -- 31
        { type = "TURNIN", quest = 1149, questName = "Test of Faith", npc = 2986, npcName = "Dorn Plainstalker", map = 1441, zone = "Thousand Needles", x = 54, y = 41.5 }, -- 32
        { type = "ACCEPT", quest = 1150, questName = "Test of Endurance", npc = 2986, npcName = "Dorn Plainstalker", map = 1441, zone = "Thousand Needles", x = 54, y = 41.5 }, -- 33
        { type = "KILL", quest = 1150, questName = "Test of Endurance", npc = 4490, target = "Grenka Bloodscreech", map = 1441, zone = "Thousand Needles", x = 26.8, y = 55.4, near = true, note = "loot Grenka's Claw" }, -- 34
        { type = "TURNIN", quest = 1150, questName = "Test of Endurance", npc = 2986, npcName = "Dorn Plainstalker", map = 1441, zone = "Thousand Needles", x = 54, y = 41.5 }, -- 35
        { type = "ACCEPT", quest = 1151, questName = "Test of Strength", npc = 2986, npcName = "Dorn Plainstalker", map = 1441, zone = "Thousand Needles", x = 54, y = 41.5, optional = true, note = "elite target - bring a group (optional)" }, -- 36
        { type = "KILL", quest = 1151, questName = "Test of Strength", npc = 4499, target = "Rok'Alim the Pounder", map = 1441, zone = "Thousand Needles", x = 17.1, y = 38.1, optional = true, near = true, note = "ELITE - loot Fragments of Rok'Alim (group quest, optional)" }, -- 37
        { type = "TURNIN", quest = 1151, questName = "Test of Strength", npc = 2986, npcName = "Dorn Plainstalker", map = 1441, zone = "Thousand Needles", x = 54, y = 41.5, optional = true }, -- 38
        { type = "ACCEPT", quest = 1152, questName = "Test of Lore", npc = 2986, npcName = "Dorn Plainstalker", map = 1441, zone = "Thousand Needles", x = 54, y = 41.5 }, -- 39
        { type = "TURNIN", quest = 5062, questName = "Sacred Fire", npc = 4046, npcName = "Magatha Grimtotem", map = 1456, zone = "Thunder Bluff", x = 69.9, y = 30.9 }, -- 40
        { type = "TURNIN", quest = 1152, questName = "Test of Lore", npc = 4489, npcName = "Braug Dimspirit", map = 1442, zone = "Stonetalon Mountains", x = 78.8, y = 45.7 }, -- 41
        { type = "GRIND", level = 28, note = "the next quests need level 28" }, -- 42
        { type = "ACCEPT", quest = 1175, questName = "A Bump in the Road", npc = 4629, npcName = "Trackmaster Zherin", map = 1441, zone = "Thousand Needles", x = 81.6, y = 78 }, -- 43
        { type = "ACCEPT", quest = 1176, questName = "Load Lightening", npc = 4630, npcName = "Pozzik", map = 1441, zone = "Thousand Needles", x = 80.2, y = 75.9 }, -- 44
        { type = "ACCEPT", quest = 1104, questName = "Salt Flat Venom", npc = 4454, npcName = "Fizzle Brassbolts", map = 1441, zone = "Thousand Needles", x = 78.1, y = 77.1 }, -- 45
        { type = "ACCEPT", quest = 1105, questName = "Hardened Shells", npc = 4453, npcName = "Wizzle Brassbolts", map = 1441, zone = "Thousand Needles", x = 78.1, y = 77.1 }, -- 46
        { type = "ACCEPT", quest = 1110, questName = "Rocket Car Parts", npc = 4452, npcName = "Kravel Koalbeard", map = 1441, zone = "Thousand Needles", x = 77.8, y = 77.3 }, -- 47
        { type = "ACCEPT", quest = 5762, questName = "Hemet Nesingwary", npc = 4452, npcName = "Kravel Koalbeard", map = 1441, zone = "Thousand Needles", x = 77.8, y = 77.3 }, -- 48
        { type = "COLLECT", quest = 1104, questName = "Salt Flat Venom", target = "Salty Scorpid Venom", map = 1441, zone = "Thousand Needles", x = 82.8, y = 79.7, near = true }, -- 49
        { type = "COLLECT", quest = 1105, questName = "Hardened Shells", target = "Hardened Tortoise Shell", map = 1441, zone = "Thousand Needles", x = 84.8, y = 81.8, near = true }, -- 50
        { type = "KILL", quest = 1175, questName = "A Bump in the Road", npc = 4150, target = "Saltstone Gazer", map = 1441, zone = "Thousand Needles", x = 83.5, y = 78.8, near = true }, -- 51
        { type = "COLLECT", quest = 1176, questName = "Load Lightening", target = "Hollow Vulture Bone", map = 1441, zone = "Thousand Needles", x = 83, y = 70.7, near = true }, -- 52
        { type = "KILL", quest = 1175, questName = "A Bump in the Road", npc = 4151, target = "Saltstone Crystalhide", map = 1441, zone = "Thousand Needles", x = 80, y = 70.5, near = true }, -- 53
        { type = "KILL", quest = 1175, questName = "A Bump in the Road", npc = 4147, target = "Saltstone Basilisk", map = 1441, zone = "Thousand Needles", x = 80.6, y = 64.2, near = true }, -- 54
        { type = "COLLECT", quest = 1110, questName = "Rocket Car Parts", target = "Rocket Car Parts", map = 1441, zone = "Thousand Needles", x = 87.6, y = 62.9, near = true }, -- 55
        { type = "TURNIN", quest = 1176, questName = "Load Lightening", npc = 4630, npcName = "Pozzik", map = 1441, zone = "Thousand Needles", x = 80.2, y = 75.9 }, -- 56
        { type = "ACCEPT", quest = 1178, questName = "Goblin Sponsorship", npc = 4630, npcName = "Pozzik", map = 1441, zone = "Thousand Needles", x = 80.2, y = 75.9 }, -- 57
        { type = "TURNIN", quest = 1104, questName = "Salt Flat Venom", npc = 4454, npcName = "Fizzle Brassbolts", map = 1441, zone = "Thousand Needles", x = 78.1, y = 77.1 }, -- 58
        { type = "TURNIN", quest = 1105, questName = "Hardened Shells", npc = 4453, npcName = "Wizzle Brassbolts", map = 1441, zone = "Thousand Needles", x = 78.1, y = 77.1 }, -- 59
        { type = "TURNIN", quest = 1175, questName = "A Bump in the Road", npc = 4629, npcName = "Trackmaster Zherin", map = 1441, zone = "Thousand Needles", x = 81.6, y = 78 }, -- 60
        { type = "TURNIN", quest = 1110, questName = "Rocket Car Parts", npc = 4452, npcName = "Kravel Koalbeard", map = 1441, zone = "Thousand Needles", x = 77.8, y = 77.3 }, -- 61
        { type = "ACCEPT", quest = 1106, questName = "Martek the Exiled", npc = 4454, npcName = "Fizzle Brassbolts", map = 1441, zone = "Thousand Needles", x = 78.1, y = 77.1 }, -- 62
        { type = "TURNIN", quest = 1178, questName = "Goblin Sponsorship", npc = 3391, npcName = "Gazlowe", map = 1413, zone = "The Barrens", x = 62.7, y = 36.2 }, -- 63
        { type = "TURNIN", quest = 5762, questName = "Hemet Nesingwary", npc = 715, npcName = "Hemet Nesingwary", map = 1434, zone = "Stranglethorn Vale", x = 35.7, y = 10.8 }, -- 64
        { type = "TURNIN", quest = 1106, questName = "Martek the Exiled", npc = 4618, npcName = "Martek the Exiled", map = 1418, zone = "Badlands", x = 42.2, y = 52.7 }, -- 65
        { type = "GRIND", level = 30, note = "the next quests need level 30" }, -- 66
        { type = "ACCEPT", quest = 1111, questName = "Wharfmaster Dizzywig", npc = 4452, npcName = "Kravel Koalbeard", map = 1441, zone = "Thousand Needles", x = 77.8, y = 77.3 }, -- 67
        { type = "TURNIN", quest = 1111, questName = "Wharfmaster Dizzywig", npc = 3453, npcName = "Wharfmaster Dizzywig", map = 1413, zone = "The Barrens", x = 63.4, y = 38.5 }, -- 68
        { type = "GRIND", level = 32, note = "the next quests need level 32" }, -- 69
        { type = "ACCEPT", quest = 5361, questName = "Family Tree", npc = 10537, npcName = "Cliffwatcher Longhorn", map = 1441, zone = "Thousand Needles", x = 45.7, y = 50.7 }, -- 70
        { type = "TURNIN", quest = 5361, questName = "Family Tree", npc = 11259, npcName = "Nataka Longhorn", map = 1443, zone = "Desolace", x = 55.4, y = 55.8 }, -- 71
    },
})
