-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_FELWOOD.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_FELWOOD",
    name = "Felwood 48-55 (Alliance)",
    version = 1,
    faction = "Alliance",
    minLevel = 48,
    maxLevel = 55,
    next = "GEN_ALLIANCE_BURNING_STEPPES",
    author = "ForeverGuide route generator",
    notes = "Auto-generated from the quest database: 15 quests, 45 steps, model reaches level 49. Not a speedrun route - a sensible order; the engine adapts as you play.",
    steps = {
        { type = "ACCEPT", quest = 8460, questName = "Timbermaw Ally", npc = 11554, npcName = "Grazle", map = 1448, zone = "Felwood", x = 50.9, y = 85 }, -- 1
        { type = "ACCEPT", quest = 5155, questName = "Forces of Jaedenar", npc = 10922, npcName = "Greta Mosshoof", map = 1448, zone = "Felwood", x = 51.2, y = 82.1 }, -- 2
        { type = "ACCEPT", quest = 5156, questName = "Verifying the Corruption", npc = 10921, npcName = "Taronn Redfeather", map = 1448, zone = "Felwood", x = 50.9, y = 81.6 }, -- 3
        { type = "ACCEPT", quest = 4421, questName = "The Corruption of the Jadefire", npc = 9116, npcName = "Eridan Bluewind", map = 1448, zone = "Felwood", x = 51.4, y = 81.5 }, -- 4
        { type = "ACCEPT", quest = 4101, questName = "Cleansing Felwood", npc = 9528, npcName = "Arathandris Silversky", map = 1448, zone = "Felwood", x = 54.2, y = 86.8 }, -- 5
        { type = "KILL", quest = 8460, questName = "Timbermaw Ally", npc = 7153, target = "Deadwood Warrior / Deadwood Gardener / Deadwood Pathfinder", map = 1448, zone = "Felwood", x = 49.7, y = 88.2 }, -- 6
        { type = "KILL", quest = 4421, questName = "The Corruption of the Jadefire", npc = 7109, target = "Jadefire Felsworn", map = 1448, zone = "Felwood", x = 44.2, y = 86.4 }, -- 7
        { type = "KILL", quest = 4421, questName = "The Corruption of the Jadefire", npc = 7106, target = "Jadefire Rogue / Jadefire Shadowstalker", map = 1448, zone = "Felwood", x = 38.1, y = 69.5 }, -- 8
        { type = "KILL", quest = 5155, questName = "Forces of Jaedenar", npc = 7112, target = "Jaedenar Cultist / Jaedenar Adept", map = 1448, zone = "Felwood", x = 38.1, y = 62.2 }, -- 9
        { type = "TURNIN", quest = 8460, questName = "Timbermaw Ally", npc = 11554, npcName = "Grazle", map = 1448, zone = "Felwood", x = 50.9, y = 85 }, -- 10
        { type = "ACCEPT", quest = 8462, questName = "Speak to Nafien", npc = 11554, npcName = "Grazle", map = 1448, zone = "Felwood", x = 50.9, y = 85 }, -- 11
        { type = "KILL", quest = 5155, questName = "Forces of Jaedenar", npc = 7125, target = "Jaedenar Hound", map = 1448, zone = "Felwood", x = 38.7, y = 61.9 }, -- 12
        { type = "COMPLETE", quest = 5156, questName = "Verifying the Corruption", npc = 9878, target = "Entropic Beast / Entropic Horror / Explore the craters in Shatter Scar Vale", map = 1448, zone = "Felwood", x = 41.3, y = 43.8 }, -- 13
        { type = "COLLECT", quest = 4101, questName = "Cleansing Felwood", target = "Blood Amber", map = 1448, zone = "Felwood", x = 57.2, y = 21.9 }, -- 14
        { type = "TURNIN", quest = 8462, questName = "Speak to Nafien", npc = 15395, npcName = "Nafien", map = 1448, zone = "Felwood", x = 64.8, y = 8.1 }, -- 15
        { type = "ACCEPT", quest = 8461, questName = "Deadwood of the North", npc = 15395, npcName = "Nafien", map = 1448, zone = "Felwood", x = 64.8, y = 8.1 }, -- 16
        { type = "KILL", quest = 8461, questName = "Deadwood of the North", npc = 7157, target = "Deadwood Avenger / Deadwood Den Watcher / Deadwood Shaman", map = 1448, zone = "Felwood", x = 63.7, y = 8.2 }, -- 17
        { type = "TURNIN", quest = 8461, questName = "Deadwood of the North", npc = 15395, npcName = "Nafien", map = 1448, zone = "Felwood", x = 64.8, y = 8.1 }, -- 18
        { type = "ACCEPT", quest = 8465, questName = "Speak to Salfa", npc = 15395, npcName = "Nafien", map = 1448, zone = "Felwood", x = 64.8, y = 8.1 }, -- 19
        { type = "ACCEPT", quest = 8481, questName = "The Root of All Evil", npc = 11555, npcName = "Gorn One Eye", map = 1448, zone = "Felwood", x = 65.2, y = 2.7 }, -- 20
        { type = "TURNIN", quest = 8481, questName = "The Root of All Evil", npc = 11555, npcName = "Gorn One Eye", map = 1448, zone = "Felwood", x = 65.2, y = 2.7 }, -- 21
        { type = "ACCEPT", quest = 8484, questName = "The Brokering of Peace", npc = 11555, npcName = "Gorn One Eye", map = 1448, zone = "Felwood", x = 65.2, y = 2.7 }, -- 22
        { type = "KILL", quest = 5155, questName = "Forces of Jaedenar", npc = 7113, target = "Jaedenar Guardian", map = 1448, zone = "Felwood", x = 38.5, y = 57.7 }, -- 23
        { type = "KILL", quest = 4421, questName = "The Corruption of the Jadefire", npc = 9454, target = "Xavathras", map = 1448, zone = "Felwood", x = 32.2, y = 67.1 }, -- 24
        { type = "TURNIN", quest = 5156, questName = "Verifying the Corruption", npc = 10921, npcName = "Taronn Redfeather", map = 1448, zone = "Felwood", x = 50.9, y = 81.6 }, -- 25
        { type = "TURNIN", quest = 4421, questName = "The Corruption of the Jadefire", npc = 9116, npcName = "Eridan Bluewind", map = 1448, zone = "Felwood", x = 51.4, y = 81.5 }, -- 26
        { type = "TURNIN", quest = 5155, questName = "Forces of Jaedenar", npc = 10922, npcName = "Greta Mosshoof", map = 1448, zone = "Felwood", x = 51.2, y = 82.1 }, -- 27
        { type = "ACCEPT", quest = 5157, questName = "Collection of the Corrupt Water", npc = 10922, npcName = "Greta Mosshoof", map = 1448, zone = "Felwood", x = 51.2, y = 82.1 }, -- 28
        { type = "ACCEPT", quest = 4906, questName = "Further Corruption", npc = 9116, npcName = "Eridan Bluewind", map = 1448, zone = "Felwood", x = 51.4, y = 81.5 }, -- 29
        { type = "TURNIN", quest = 4101, questName = "Cleansing Felwood", npc = 9528, npcName = "Arathandris Silversky", map = 1448, zone = "Felwood", x = 54.2, y = 86.8 }, -- 30
        { type = "ACCEPT", quest = 5882, questName = "Salve via Hunting", npc = 9528, npcName = "Arathandris Silversky", map = 1448, zone = "Felwood", x = 54.2, y = 86.8 }, -- 31
        { type = "COLLECT", quest = 5882, questName = "Salve via Hunting", target = "Corrupted Soul Shard", map = 1448, zone = "Felwood", x = 55, y = 85.8 }, -- 32
        { type = "TURNIN", quest = 5882, questName = "Salve via Hunting", npc = 9528, npcName = "Arathandris Silversky", map = 1448, zone = "Felwood", x = 54.2, y = 86.8 }, -- 33
        { type = "COLLECT", quest = 5157, questName = "Collection of the Corrupt Water", target = "Corrupt Moonwell Water", map = 1448, zone = "Felwood", x = 35.2, y = 59.8 }, -- 34
        { type = "TURNIN", quest = 5157, questName = "Collection of the Corrupt Water", npc = 10922, npcName = "Greta Mosshoof", map = 1448, zone = "Felwood", x = 51.2, y = 82.1 }, -- 35
        { type = "ACCEPT", quest = 5158, questName = "Seeking Spiritual Aid", npc = 10922, npcName = "Greta Mosshoof", map = 1448, zone = "Felwood", x = 51.2, y = 82.1 }, -- 36
        { type = "KILL", quest = 4906, questName = "Further Corruption", npc = 7111, target = "Jadefire Hellcaller", map = 1448, zone = "Felwood", x = 36.8, y = 56.5 }, -- 37
        { type = "KILL", quest = 4906, questName = "Further Corruption", npc = 10648, target = "Xavaric / Jadefire Betrayer", map = 1448, zone = "Felwood", x = 39.1, y = 22.4 }, -- 38
        { type = "KILL", quest = 4906, questName = "Further Corruption", npc = 7107, target = "Jadefire Trickster", map = 1448, zone = "Felwood", x = 41, y = 20.4 }, -- 39
        { type = "TURNIN", quest = 4906, questName = "Further Corruption", npc = 9116, npcName = "Eridan Bluewind", map = 1448, zone = "Felwood", x = 51.4, y = 81.5 }, -- 40
        { type = "TURNIN", quest = 5158, questName = "Seeking Spiritual Aid", npc = 5901, npcName = "Islen Waterseer", map = 1413, zone = "The Barrens", x = 65.8, y = 43.8 }, -- 41
        { type = "TURNIN", quest = 8465, questName = "Speak to Salfa", npc = 11556, npcName = "Salfa", map = 1452, zone = "Winterspring", x = 27.7, y = 34.5 }, -- 42
        { type = "TURNIN", quest = 8484, questName = "The Brokering of Peace", npc = 2784, npcName = "King Magni Bronzebeard", map = 1455, zone = "Ironforge", x = 39.1, y = 56.2 }, -- 43
        { type = "ACCEPT", quest = 6031, questName = "Runecloth", npc = 11557, npcName = "Meilosh", map = 1448, zone = "Felwood", x = 65.7, y = 2.8 }, -- 44
        { type = "TURNIN", quest = 6031, questName = "Runecloth", npc = 11557, npcName = "Meilosh", map = 1448, zone = "Felwood", x = 65.7, y = 2.8 }, -- 45
    },
})
