-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_ORC_30_THE_HINTERLANDS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_ORC_30_THE_HINTERLANDS",
    name = "30. The Hinterlands 49-49 (Orc)",
    version = 2,
    faction = "Horde",
    race = { "Orc", "Troll" },
    minLevel = 49,
    maxLevel = 49,
    map = 1425,
    zone = "The Hinterlands",
    next = "GEN_HORDE_ORC_31_EASTERN_PLAGUELANDS",
    author = "ForeverGuide route planner",
    notes = "Chapter 30 of the Orc route: level 49 to 49, 10 steps, ~22 min of play in the model (45860 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1425, zone = "The Hinterlands", x = 50.3, y = 89.6, radius = 60, note = "travel to The Hinterlands (The Hinterlands)" }, -- 1
        { type = "ACCEPT", quest = 7849, questName = "Separation Anxiety", npc = 14741, npcName = "Huntsman Markhor", map = 1425, zone = "The Hinterlands", x = 79.2, y = 79.5 }, -- 2
        { type = "ACCEPT", quest = 7850, questName = "Dark Vessels", npc = 14736, npcName = "Primal Torntusk", map = 1425, zone = "The Hinterlands", x = 78.2, y = 81.2 }, -- 3
        { type = "ACCEPT", quest = 7845, questName = "Kidnapped Elder Torntusk!", npc = 14736, npcName = "Primal Torntusk", map = 1425, zone = "The Hinterlands", x = 78.2, y = 81.2 }, -- 4
        { type = "COLLECT", quest = 7850, questName = "Dark Vessels", target = "Vessel of Tainted Blood", count = 10, map = 1425, zone = "The Hinterlands", x = 67.9, y = 75.8, near = true }, -- 5
        { type = "COLLECT", quest = 7849, questName = "Separation Anxiety", target = "Huntsman Malkhor's Bones", map = 1425, zone = "The Hinterlands", x = 62.1, y = 75.4 }, -- 6
        { type = "TURNIN", quest = 7845, questName = "Kidnapped Elder Torntusk!", npc = 14757, npcName = "Elder Torntusk", map = 1425, zone = "The Hinterlands", x = 59.7, y = 77.8 }, -- 7
        { type = "COLLECT", quest = 7849, questName = "Separation Anxiety", target = "Huntsman Malkhor's Skull", map = 1425, zone = "The Hinterlands", x = 58.6, y = 64.8 }, -- 8
        { type = "TURNIN", quest = 7850, questName = "Dark Vessels", npc = 14736, npcName = "Primal Torntusk", map = 1425, zone = "The Hinterlands", x = 78.2, y = 81.2 }, -- 9
        { type = "TURNIN", quest = 7849, questName = "Separation Anxiety", npc = 14741, npcName = "Huntsman Markhor", map = 1425, zone = "The Hinterlands", x = 79.2, y = 79.5 }, -- 10
    },
})
