-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_SKYBORNE_08_BADLANDS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_SKYBORNE_08_BADLANDS",
    name = "8. Badlands 34-35 (Skyborne)",
    version = 2,
    faction = "Horde",
    race = { "Skyborne" },
    minLevel = 34,
    maxLevel = 35,
    map = 1418,
    zone = "Badlands",
    next = "GEN_HORDE_SKYBORNE_09_ARATHI_HIGHLANDS",
    author = "ForeverGuide route planner",
    notes = "Chapter 8 of the Skyborne route: level 34 to 35, 41 steps, ~178 min of play in the model (33122 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1418, zone = "Badlands", x = 3.5, y = 47.0, radius = 60, note = "travel to Badlands (Badlands)" }, -- 1
        { type = "NOTE", map = 1418, zone = "Badlands", x = 3.5, y = 47.0, text = "set your hearthstone at the inn in Badlands (if there is one)" }, -- 2
        { type = "ACCEPT", quest = 1419, questName = "Coyote Thieves", npc = 5394, npcName = "Neeka Bloodscar", map = 1418, zone = "Badlands", x = 6.5, y = 47.2 }, -- 3
        { type = "COLLECT", quest = 1419, questName = "Coyote Thieves", target = "Coyote Jawbone", count = 30, map = 1418, zone = "Badlands", x = 11.2, y = 63.1, near = true }, -- 4
        { type = "TURNIN", quest = 1419, questName = "Coyote Thieves", npc = 5394, npcName = "Neeka Bloodscar", map = 1418, zone = "Badlands", x = 6.5, y = 47.2 }, -- 5
        { type = "ACCEPT", quest = 710, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 6
        { type = "ACCEPT", quest = 713, questName = "Coolant Heads Prevail", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 7
        { type = "TURNIN", quest = 713, questName = "Coolant Heads Prevail", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 8
        { type = "ACCEPT", quest = 714, questName = "Gyro... What?", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 9
        { type = "TURNIN", quest = 714, questName = "Gyro... What?", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 10
        { type = "KILL", quest = 710, questName = "Study of the Elements: Rock", npc = 2735, target = "Lesser Rock Elemental", count = 10, map = 1418, zone = "Badlands", x = 23.5, y = 45.5, near = true, note = "loot Small Stone Shard" }, -- 11
        { type = "TURNIN", quest = 710, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 12
        { type = "ACCEPT", quest = 711, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 13
        { type = "KILL", quest = 711, questName = "Study of the Elements: Rock", npc = 92, target = "Rock Elemental", count = 3, map = 1418, zone = "Badlands", x = 13.4, y = 33.4, near = true, note = "loot Large Stone Slab" }, -- 14
        { type = "TURNIN", quest = 711, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 15
        { type = "ACCEPT", quest = 712, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 16
        { type = "KILL", quest = 712, questName = "Study of the Elements: Rock", npc = 2736, target = "Greater Rock Elemental", count = 5, map = 1418, zone = "Badlands", x = 6.6, y = 76.3, near = true, note = "loot Bracers of Rock Binding" }, -- 17
        { type = "TURNIN", quest = 712, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 18
        { type = "ACCEPT", quest = 734, questName = "This Is Going to Be Hard", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 19
        { type = "ACCEPT", quest = 716, questName = "Stone Is Better than Cloth", npc = 2920, npcName = "Lucien Tosselwrench", map = 1418, zone = "Badlands", x = 25.8, y = 44.2 }, -- 20
        { type = "TURNIN", quest = 716, questName = "Stone Is Better than Cloth", npc = 2920, npcName = "Lucien Tosselwrench", map = 1418, zone = "Badlands", x = 25.8, y = 44.2 }, -- 21
        { type = "TURNIN", quest = 734, questName = "This Is Going to Be Hard", npc = 2920, npcName = "Lucien Tosselwrench", map = 1418, zone = "Badlands", x = 25.8, y = 44.2 }, -- 22
        { type = "ACCEPT", quest = 777, questName = "This Is Going to Be Hard", npc = 2920, npcName = "Lucien Tosselwrench", map = 1418, zone = "Badlands", x = 25.8, y = 44.2 }, -- 23
        { type = "TURNIN", quest = 777, questName = "This Is Going to Be Hard", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 24
        { type = "ACCEPT", quest = 778, questName = "This Is Going to Be Hard", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 25
        { type = "KILL", quest = 778, questName = "This Is Going to Be Hard", npc = 2919, target = "Fam'retor Guardian", map = 1418, zone = "Badlands", x = 26, y = 45.8, note = "loot Lotwil's Shackles of Elemental Binding" }, -- 26
        { type = "TURNIN", quest = 778, questName = "This Is Going to Be Hard", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 27
        { type = "ACCEPT", quest = 2418, questName = "Power Stones", npc = 2817, npcName = "Rigglefuzz", map = 1418, zone = "Badlands", x = 42.4, y = 52.9 }, -- 28
        { type = "ACCEPT", quest = 703, questName = "Barbecued Buzzard Wings", npc = 2817, npcName = "Rigglefuzz", map = 1418, zone = "Badlands", x = 42.4, y = 52.9 }, -- 29
        { type = "COLLECT", quest = 2418, questName = "Power Stones", target = "Dentrium Power Stone / An'Alleum Power Stone", count = 8, map = 1418, zone = "Badlands", x = 51.2, y = 27.2, near = true }, -- 30
        { type = "COLLECT", quest = 703, questName = "Barbecued Buzzard Wings", target = "Buzzard Wing", count = 4, map = 1418, zone = "Badlands", x = 48.9, y = 27.4, near = true }, -- 31
        { type = "TURNIN", quest = 2418, questName = "Power Stones", npc = 2817, npcName = "Rigglefuzz", map = 1418, zone = "Badlands", x = 42.4, y = 52.9 }, -- 32
        { type = "TURNIN", quest = 703, questName = "Barbecued Buzzard Wings", npc = 2817, npcName = "Rigglefuzz", map = 1418, zone = "Badlands", x = 42.4, y = 52.9 }, -- 33
        { type = "ACCEPT", quest = 2258, questName = "Badlands Reagent Run", npc = 6868, npcName = "Jarkal Mossmeld", map = 1418, zone = "Badlands", x = 2.4, y = 46.1 }, -- 34
        { type = "COLLECT", quest = 2258, questName = "Badlands Reagent Run", target = "Rock Elemental Shard", count = 5, map = 1418, zone = "Badlands", x = 13.3, y = 38, near = true }, -- 35
        { type = "COLLECT", quest = 2258, questName = "Badlands Reagent Run", target = "Buzzard Gizzard", count = 5, map = 1418, zone = "Badlands", x = 15.5, y = 58.5, near = true }, -- 36
        { type = "COLLECT", quest = 2258, questName = "Badlands Reagent Run", target = "Crag Coyote Fang", count = 10, map = 1418, zone = "Badlands", x = 11.2, y = 63.1, near = true }, -- 37
        { type = "TURNIN", quest = 2258, questName = "Badlands Reagent Run", npc = 6868, npcName = "Jarkal Mossmeld", map = 1418, zone = "Badlands", x = 2.4, y = 46.1 }, -- 38
        { type = "ACCEPT", quest = 2202, questName = "Uldaman Reagent Run", npc = 6868, npcName = "Jarkal Mossmeld", map = 1418, zone = "Badlands", x = 2.4, y = 46.1 }, -- 39
        { type = "COLLECT", quest = 2202, questName = "Uldaman Reagent Run", target = "Magenta Fungus Cap", count = 12, map = 1418, zone = "Badlands", x = 34, y = 24.4, near = true }, -- 40
        { type = "TURNIN", quest = 2202, questName = "Uldaman Reagent Run", npc = 6868, npcName = "Jarkal Mossmeld", map = 1418, zone = "Badlands", x = 2.4, y = 46.1 }, -- 41
    },
})
