-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_SCOURGE_41_SILITHUS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_SCOURGE_41_SILITHUS",
    name = "41. Silithus 53-54 (Undead)",
    version = 2,
    faction = "Horde",
    race = { "Scourge" },
    minLevel = 53,
    maxLevel = 54,
    map = 1451,
    zone = "Silithus",
    next = "GEN_HORDE_SCOURGE_42_EASTERN_PLAGUELANDS",
    author = "ForeverGuide route planner",
    notes = "Chapter 41 of the Scourge route: level 53 to 54, 40 steps, ~171 min of play in the model (46796 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1452, zone = "Winterspring", x = 61.4, y = 38.2, radius = 60, note = "use your hearthstone (Winterspring)" }, -- 1
        { type = "TRAVEL", map = 1451, zone = "Silithus", x = 50.1, y = 37.6, radius = 60, note = "travel to Silithus (Silithus)" }, -- 2
        { type = "NOTE", map = 1451, zone = "Silithus", x = 50.1, y = 37.6, text = "set your hearthstone at the inn in Silithus (if there is one)" }, -- 3
        { type = "ACCEPT", quest = 8280, questName = "Securing the Supply Lines", npc = 15191, npcName = "Windcaller Proudhorn", map = 1451, zone = "Silithus", x = 51.2, y = 38.3 }, -- 4
        { type = "ACCEPT", quest = 8277, questName = "Deadly Desert Venom", npc = 15189, npcName = "Beetix Ficklespragg", map = 1451, zone = "Silithus", x = 51.6, y = 38.6 }, -- 5
        { type = "ACCEPT", quest = 8284, questName = "The Twilight Mystery", npc = 15183, npcName = "Geologist Larksbane", map = 1451, zone = "Silithus", x = 49.7, y = 37.5 }, -- 6
        { type = "ACCEPT", quest = 9416, questName = "Report to General Kirika", npc = 17081, npcName = "Scout Bloodfist", map = 1451, zone = "Silithus", x = 49, y = 36.7 }, -- 7
        { type = "KILL", quest = 8277, questName = "Deadly Desert Venom", npc = 11735, target = "Stonelash Scorpid", count = 8, map = 1451, zone = "Silithus", x = 43, y = 41.2, near = true, note = "loot Stonelash Scorpid Stinger" }, -- 8
        { type = "KILL", quest = 8277, questName = "Deadly Desert Venom", npc = 11738, target = "Sand Skitterer", count = 8, map = 1451, zone = "Silithus", x = 42.3, y = 35.1, near = true, note = "loot Sand Skitterer Fang" }, -- 9
        { type = "KILL", quest = 8280, questName = "Securing the Supply Lines", npc = 11740, target = "Dredge Striker", count = 15, map = 1451, zone = "Silithus", x = 38.2, y = 34.3, near = true }, -- 10
        { type = "COLLECT", quest = 8284, questName = "The Twilight Mystery", target = "Twilight Tablet Fragment", count = 8, map = 1451, zone = "Silithus", x = 26.4, y = 15.9, near = true }, -- 11
        { type = "TURNIN", quest = 8280, questName = "Securing the Supply Lines", npc = 15191, npcName = "Windcaller Proudhorn", map = 1451, zone = "Silithus", x = 51.2, y = 38.3 }, -- 12
        { type = "ACCEPT", quest = 8281, questName = "Stepping Up Security", npc = 15191, npcName = "Windcaller Proudhorn", map = 1451, zone = "Silithus", x = 51.2, y = 38.3 }, -- 13
        { type = "TURNIN", quest = 8277, questName = "Deadly Desert Venom", npc = 15189, npcName = "Beetix Ficklespragg", map = 1451, zone = "Silithus", x = 51.6, y = 38.6 }, -- 14
        { type = "TURNIN", quest = 8284, questName = "The Twilight Mystery", npc = 15183, npcName = "Geologist Larksbane", map = 1451, zone = "Silithus", x = 49.7, y = 37.5 }, -- 15
        { type = "ACCEPT", quest = 8278, questName = "Noggle's Last Hope", npc = 15189, npcName = "Beetix Ficklespragg", map = 1451, zone = "Silithus", x = 51.6, y = 38.6 }, -- 16
        { type = "ACCEPT", quest = 8285, questName = "The Deserter", npc = 15183, npcName = "Geologist Larksbane", map = 1451, zone = "Silithus", x = 49.7, y = 37.5 }, -- 17
        { type = "KILL", quest = 8281, questName = "Stepping Up Security", npc = 11741, target = "Dredge Crusher", count = 20, map = 1451, zone = "Silithus", x = 40.9, y = 49.3, near = true }, -- 18
        { type = "KILL", quest = 8278, questName = "Noggle's Last Hope", npc = 11736, target = "Stonelash Pincer", count = 3, map = 1451, zone = "Silithus", x = 38, y = 52.3, near = true, note = "loot Stonelash Pincer Stinger" }, -- 19
        { type = "KILL", quest = 8278, questName = "Noggle's Last Hope", npc = 11737, target = "Stonelash Flayer / Rock Stalker", count = 3, map = 1451, zone = "Silithus", x = 39.5, y = 68.6, near = true, note = "loot Stonelash Flayer Stinger" }, -- 20
        { type = "TURNIN", quest = 8278, questName = "Noggle's Last Hope", npc = 15189, npcName = "Beetix Ficklespragg", map = 1451, zone = "Silithus", x = 51.6, y = 38.6 }, -- 21
        { type = "ACCEPT", quest = 8282, questName = "Noggle's Lost Satchel", npc = 15190, npcName = "Noggle Ficklespragg", map = 1451, zone = "Silithus", x = 51.6, y = 38.5 }, -- 22
        { type = "TURNIN", quest = 8281, questName = "Stepping Up Security", npc = 15191, npcName = "Windcaller Proudhorn", map = 1451, zone = "Silithus", x = 51.2, y = 38.3 }, -- 23
        { type = "COLLECT", quest = 8282, questName = "Noggle's Lost Satchel", target = "Noggle's Satchel", map = 1451, zone = "Silithus", x = 44.6, y = 91.4 }, -- 24
        { type = "TURNIN", quest = 8282, questName = "Noggle's Lost Satchel", npc = 15190, npcName = "Noggle Ficklespragg", map = 1451, zone = "Silithus", x = 51.6, y = 38.5 }, -- 25
        { type = "TURNIN", quest = 9416, questName = "Report to General Kirika", npc = 17079, npcName = "General Kirika", map = 1451, zone = "Silithus", x = 50.8, y = 69.5 }, -- 26
        { type = "TURNIN", quest = 8285, questName = "The Deserter", npc = 15194, npcName = "Hermit Ortell", map = 1451, zone = "Silithus", x = 67.2, y = 69.8 }, -- 27
        { type = "ACCEPT", quest = 8279, questName = "The Twilight Lexicon", npc = 15194, npcName = "Hermit Ortell", map = 1451, zone = "Silithus", x = 67.2, y = 69.8 }, -- 28
        { type = "KILL", quest = 8279, questName = "The Twilight Lexicon", npc = 11804, target = "Twilight Keeper Havunth", map = 1451, zone = "Silithus", x = 40.9, y = 42.2, note = "loot Twilight Lexicon - Chapter 3" }, -- 29
        { type = "KILL", quest = 8279, questName = "The Twilight Lexicon", npc = 15200, target = "Twilight Keeper Mayna", map = 1451, zone = "Silithus", x = 26.4, y = 36.6, note = "loot Twilight Lexicon - Chapter 1" }, -- 30
        { type = "KILL", quest = 8279, questName = "The Twilight Lexicon", npc = 11803, target = "Twilight Keeper Exeter", map = 1451, zone = "Silithus", x = 16.1, y = 86.4, note = "loot Twilight Lexicon - Chapter 2" }, -- 31
        { type = "TURNIN", quest = 8279, questName = "The Twilight Lexicon", npc = 15194, npcName = "Hermit Ortell", map = 1451, zone = "Silithus", x = 67.2, y = 69.8 }, -- 32
        { type = "ACCEPT", quest = 8323, questName = "True Believers", npc = 15194, npcName = "Hermit Ortell", map = 1451, zone = "Silithus", x = 67.2, y = 69.8 }, -- 33
        { type = "ACCEPT", quest = 8287, questName = "A Terrible Purpose", npc = 15194, npcName = "Hermit Ortell", map = 1451, zone = "Silithus", x = 67.2, y = 69.8 }, -- 34
        { type = "COLLECT", quest = 8323, questName = "True Believers", target = "Encrypted Twilight Text", count = 10, map = 1451, zone = "Silithus", x = 41.5, y = 45.2, near = true }, -- 35
        { type = "TURNIN", quest = 8323, questName = "True Believers", npc = 15194, npcName = "Hermit Ortell", map = 1451, zone = "Silithus", x = 67.2, y = 69.8 }, -- 36
        { type = "ACCEPT", quest = 9422, questName = "Scouring the Desert", npc = 17079, npcName = "General Kirika", map = 1451, zone = "Silithus", x = 50.8, y = 69.5 }, -- 37
        { type = "KILL", quest = 9422, questName = "Scouring the Desert", npc = 18199, target = "Silithus Dust Turnin Quest Doodad Horde", count = 1, map = 1451, zone = "Silithus", x = 50.9, y = 69.3 }, -- 38
        { type = "TURNIN", quest = 9422, questName = "Scouring the Desert", npc = 17079, npcName = "General Kirika", map = 1451, zone = "Silithus", x = 50.8, y = 69.5 }, -- 39
        { type = "TURNIN", quest = 8287, questName = "A Terrible Purpose", npc = 15181, npcName = "Commander Mar'alith", map = 1451, zone = "Silithus", x = 49.2, y = 34.2 }, -- 40
    },
})
