-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_SKYBORNE_45_WESTERN_PLAGUELANDS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_SKYBORNE_45_WESTERN_PLAGUELANDS",
    name = "45. Western Plaguelands 55-56 (Skyborne)",
    version = 2,
    faction = "Alliance",
    race = { "Skyborne" },
    minLevel = 55,
    maxLevel = 56,
    map = 1422,
    zone = "Western Plaguelands",
    next = "GEN_ALLIANCE_SKYBORNE_46_BURNING_STEPPES",
    author = "ForeverGuide route planner",
    notes = "Chapter 45 of the Skyborne route: level 55 to 56, 12 steps, ~29 min of play in the model (59202 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1422, zone = "Western Plaguelands", x = 43.0, y = 84.1, radius = 60, note = "travel to Western Plaguelands (Western Plaguelands)" }, -- 1
        { type = "ACCEPT", quest = 5533, questName = "Scholomance", npc = 10838, npcName = "Commander Ashlam Valorfist", map = 1422, zone = "Western Plaguelands", x = 42.7, y = 84 }, -- 2
        { type = "TURNIN", quest = 5533, questName = "Scholomance", npc = 11056, npcName = "Alchemist Arbington", map = 1422, zone = "Western Plaguelands", x = 42.7, y = 83.8 }, -- 3
        { type = "ACCEPT", quest = 5537, questName = "Skeletal Fragments", npc = 11056, npcName = "Alchemist Arbington", map = 1422, zone = "Western Plaguelands", x = 42.7, y = 83.8 }, -- 4
        { type = "COLLECT", quest = 5537, questName = "Skeletal Fragments", target = "Skeletal Fragments", count = 15, map = 1422, zone = "Western Plaguelands", x = 47.3, y = 80.5, near = true }, -- 5
        { type = "TURNIN", quest = 5537, questName = "Skeletal Fragments", npc = 11056, npcName = "Alchemist Arbington", map = 1422, zone = "Western Plaguelands", x = 42.7, y = 83.8 }, -- 6
        { type = "ACCEPT", quest = 4971, questName = "A Matter of Time", npc = 10667, npcName = "Chromie", map = 1422, zone = "Western Plaguelands", x = 39.5, y = 66.8 }, -- 7
        { type = "KILL", quest = 4971, questName = "A Matter of Time", npc = 10717, target = "Temporal Parasite", count = 10, map = 1422, zone = "Western Plaguelands", x = 45.2, y = 62.8, near = true }, -- 8
        { type = "TURNIN", quest = 4971, questName = "A Matter of Time", npc = 10667, npcName = "Chromie", map = 1422, zone = "Western Plaguelands", x = 39.5, y = 66.8 }, -- 9
        { type = "ACCEPT", quest = 4972, questName = "Counting Out Time", npc = 10667, npcName = "Chromie", map = 1422, zone = "Western Plaguelands", x = 39.5, y = 66.8 }, -- 10
        { type = "COLLECT", quest = 4972, questName = "Counting Out Time", target = "Andorhal Watch", count = 5, map = 1422, zone = "Western Plaguelands", x = 40.3, y = 68.2, near = true }, -- 11
        { type = "TURNIN", quest = 4972, questName = "Counting Out Time", npc = 10667, npcName = "Chromie", map = 1422, zone = "Western Plaguelands", x = 39.5, y = 66.8 }, -- 12
    },
})
