-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_NIGHTELF_32_TANARIS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_NIGHTELF_32_TANARIS",
    name = "32. Tanaris 48-49 (Night Elf)",
    version = 2,
    faction = "Alliance",
    race = { "NightElf" },
    minLevel = 48,
    maxLevel = 49,
    map = 1446,
    zone = "Tanaris",
    next = "GEN_ALLIANCE_NIGHTELF_33_UN_GORO_CRATER",
    author = "ForeverGuide route planner",
    notes = "Chapter 32 of the NightElf route: level 48 to 49, 6 steps, ~91 min of play in the model (8726 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1446, zone = "Tanaris", x = 52.0, y = 27.4, radius = 60, note = "travel to Tanaris (Tanaris)" }, -- 1
        { type = "ACCEPT", quest = 3362, questName = "Thistleshrub Valley", npc = 7876, npcName = "Tran'rek", map = 1446, zone = "Tanaris", x = 51.6, y = 26.8 }, -- 2
        { type = "TURNIN", quest = 3445, questName = "The Sunken Temple", npc = 7771, npcName = "Marvon Rivetseeker", map = 1446, zone = "Tanaris", x = 52.7, y = 45.9 }, -- 3
        { type = "KILL", quest = 3362, questName = "Thistleshrub Valley", npc = 5490, target = "Gnarled Thistleshrub / Thistleshrub Rootshaper", count = 8, map = 1446, zone = "Tanaris", x = 31.2, y = 65.5, near = true }, -- 4
        { type = "TURNIN", quest = 3362, questName = "Thistleshrub Valley", npc = 7876, npcName = "Tran'rek", map = 1446, zone = "Tanaris", x = 51.6, y = 26.8 }, -- 5
        { type = "GRIND", npc = 5431, target = "Surf Glider", level = 49, map = 1446, zone = "Tanaris", x = 67, y = 57.5, near = true, note = "grind Surf Glider (level 48-50) to level 49 - nothing worth questing at 48" }, -- 6
    },
})
