-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_HUMAN_32_FELWOOD.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_HUMAN_32_FELWOOD",
    name = "32. Felwood 49-49 (Human)",
    version = 2,
    faction = "Alliance",
    race = { "Human" },
    minLevel = 49,
    maxLevel = 49,
    map = 1448,
    zone = "Felwood",
    next = "GEN_ALLIANCE_HUMAN_33_WINTERSPRING",
    author = "ForeverGuide route planner",
    notes = "Chapter 32 of the Human route: level 49 to 49, 12 steps, ~61 min of play in the model (30154 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1447, zone = "Azshara", x = 60.8, y = 66.4, radius = 60, note = "use your hearthstone (Azshara)" }, -- 1
        { type = "TRAVEL", map = 1448, zone = "Felwood", x = 51.3, y = 81.9, radius = 60, note = "travel to Felwood (Felwood)" }, -- 2
        { type = "ACCEPT", quest = 4421, questName = "The Corruption of the Jadefire", npc = 9116, npcName = "Eridan Bluewind", map = 1448, zone = "Felwood", x = 51.4, y = 81.5 }, -- 3
        { type = "KILL", quest = 4421, questName = "The Corruption of the Jadefire", npc = 7109, target = "Jadefire Felsworn", count = 11, map = 1448, zone = "Felwood", x = 44.2, y = 86.4, near = true }, -- 4
        { type = "KILL", quest = 4421, questName = "The Corruption of the Jadefire", npc = 7106, target = "Jadefire Rogue / Jadefire Shadowstalker", count = 11, map = 1448, zone = "Felwood", x = 38.1, y = 69.5, near = true }, -- 5
        { type = "KILL", quest = 4421, questName = "The Corruption of the Jadefire", npc = 9454, target = "Xavathras", count = 1, map = 1448, zone = "Felwood", x = 32.2, y = 67.1 }, -- 6
        { type = "TURNIN", quest = 4421, questName = "The Corruption of the Jadefire", npc = 9116, npcName = "Eridan Bluewind", map = 1448, zone = "Felwood", x = 51.4, y = 81.5 }, -- 7
        { type = "ACCEPT", quest = 4906, questName = "Further Corruption", npc = 9116, npcName = "Eridan Bluewind", map = 1448, zone = "Felwood", x = 51.4, y = 81.5 }, -- 8
        { type = "KILL", quest = 4906, questName = "Further Corruption", npc = 7111, target = "Jadefire Hellcaller", count = 8, map = 1448, zone = "Felwood", x = 36.8, y = 56.5, near = true }, -- 9
        { type = "KILL", quest = 4906, questName = "Further Corruption", npc = 10648, target = "Xavaric / Jadefire Betrayer", count = 1, map = 1448, zone = "Felwood", x = 39.1, y = 22.4 }, -- 10
        { type = "KILL", quest = 4906, questName = "Further Corruption", npc = 7107, target = "Jadefire Trickster", count = 8, map = 1448, zone = "Felwood", x = 41, y = 20.4, near = true }, -- 11
        { type = "TURNIN", quest = 4906, questName = "Further Corruption", npc = 9116, npcName = "Eridan Bluewind", map = 1448, zone = "Felwood", x = 51.4, y = 81.5 }, -- 12
    },
})
