-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_BADLANDS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_BADLANDS",
    name = "Badlands 35-45 (Horde)",
    version = 1,
    faction = "Horde",
    minLevel = 35,
    maxLevel = 45,
    next = "GEN_HORDE_SWAMP_OF_SORROWS",
    author = "ForeverGuide route generator",
    notes = "Auto-generated from the quest database: 17 quests, 48 steps, model reaches level 40. Not a speedrun route - a sensible order; the engine adapts as you play.",
    steps = {
        { type = "ACCEPT", quest = 1419, questName = "Coyote Thieves", npc = 5394, npcName = "Neeka Bloodscar", map = 1418, zone = "Badlands", x = 6.5, y = 47.2 }, -- 1
        { type = "ACCEPT", quest = 1420, questName = "Report to Helgrum", npc = 5394, npcName = "Neeka Bloodscar", map = 1418, zone = "Badlands", x = 6.5, y = 47.2 }, -- 2
        { type = "ACCEPT", quest = 2258, questName = "Badlands Reagent Run", npc = 6868, npcName = "Jarkal Mossmeld", map = 1418, zone = "Badlands", x = 2.4, y = 46.1 }, -- 3
        { type = "COLLECT", quest = 1419, questName = "Coyote Thieves", target = "Coyote Jawbone", map = 1418, zone = "Badlands", x = 11.2, y = 63.1 }, -- 4
        { type = "COLLECT", quest = 2258, questName = "Badlands Reagent Run", target = "Crag Coyote Fang", map = 1418, zone = "Badlands", x = 11.2, y = 63.1 }, -- 5
        { type = "COLLECT", quest = 2258, questName = "Badlands Reagent Run", target = "Buzzard Gizzard", map = 1418, zone = "Badlands", x = 15, y = 60.1 }, -- 6
        { type = "TURNIN", quest = 1419, questName = "Coyote Thieves", npc = 5394, npcName = "Neeka Bloodscar", map = 1418, zone = "Badlands", x = 6.5, y = 47.2 }, -- 7
        { type = "COLLECT", quest = 2258, questName = "Badlands Reagent Run", target = "Rock Elemental Shard", map = 1418, zone = "Badlands", x = 14.7, y = 41.8 }, -- 8
        { type = "TURNIN", quest = 2258, questName = "Badlands Reagent Run", npc = 6868, npcName = "Jarkal Mossmeld", map = 1418, zone = "Badlands", x = 2.4, y = 46.1 }, -- 9
        { type = "ACCEPT", quest = 2202, questName = "Uldaman Reagent Run", npc = 6868, npcName = "Jarkal Mossmeld", map = 1418, zone = "Badlands", x = 2.4, y = 46.1 }, -- 10
        { type = "ACCEPT", quest = 710, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 11
        { type = "ACCEPT", quest = 713, questName = "Coolant Heads Prevail", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 12
        { type = "TURNIN", quest = 713, questName = "Coolant Heads Prevail", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 13
        { type = "ACCEPT", quest = 714, questName = "Gyro... What?", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 14
        { type = "TURNIN", quest = 714, questName = "Gyro... What?", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 15
        { type = "KILL", quest = 710, questName = "Study of the Elements: Rock", npc = 2735, target = "Lesser Rock Elemental", map = 1418, zone = "Badlands", x = 23.5, y = 45.5, note = "loot Small Stone Shard" }, -- 16
        { type = "TURNIN", quest = 710, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 17
        { type = "ACCEPT", quest = 711, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 18
        { type = "KILL", quest = 711, questName = "Study of the Elements: Rock", npc = 92, target = "Rock Elemental", map = 1418, zone = "Badlands", x = 13.4, y = 33.4, note = "loot Large Stone Slab" }, -- 19
        { type = "COLLECT", quest = 2202, questName = "Uldaman Reagent Run", target = "Magenta Fungus Cap", map = 1418, zone = "Badlands", x = 34, y = 24.4 }, -- 20
        { type = "TURNIN", quest = 711, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 21
        { type = "ACCEPT", quest = 712, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 22
        { type = "ACCEPT", quest = 2418, questName = "Power Stones", npc = 2817, npcName = "Rigglefuzz", map = 1418, zone = "Badlands", x = 42.4, y = 52.9 }, -- 23
        { type = "ACCEPT", quest = 703, questName = "Barbecued Buzzard Wings", npc = 2817, npcName = "Rigglefuzz", map = 1418, zone = "Badlands", x = 42.4, y = 52.9 }, -- 24
        { type = "COLLECT", quest = 703, questName = "Barbecued Buzzard Wings", target = "Buzzard Wing", map = 1418, zone = "Badlands", x = 48.6, y = 55.5 }, -- 25
        { type = "TURNIN", quest = 703, questName = "Barbecued Buzzard Wings", npc = 2817, npcName = "Rigglefuzz", map = 1418, zone = "Badlands", x = 42.4, y = 52.9 }, -- 26
        { type = "KILL", quest = 712, questName = "Study of the Elements: Rock", npc = 2736, target = "Greater Rock Elemental", map = 1418, zone = "Badlands", x = 6.6, y = 76.3, note = "loot Bracers of Rock Binding" }, -- 27
        { type = "TURNIN", quest = 712, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 28
        { type = "ACCEPT", quest = 734, questName = "This Is Going to Be Hard", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 29
        { type = "ACCEPT", quest = 716, questName = "Stone Is Better than Cloth", npc = 2920, npcName = "Lucien Tosselwrench", map = 1418, zone = "Badlands", x = 25.8, y = 44.2 }, -- 30
        { type = "TURNIN", quest = 716, questName = "Stone Is Better than Cloth", npc = 2920, npcName = "Lucien Tosselwrench", map = 1418, zone = "Badlands", x = 25.8, y = 44.2 }, -- 31
        { type = "TURNIN", quest = 734, questName = "This Is Going to Be Hard", npc = 2920, npcName = "Lucien Tosselwrench", map = 1418, zone = "Badlands", x = 25.8, y = 44.2 }, -- 32
        { type = "ACCEPT", quest = 777, questName = "This Is Going to Be Hard", npc = 2920, npcName = "Lucien Tosselwrench", map = 1418, zone = "Badlands", x = 25.8, y = 44.2 }, -- 33
        { type = "TURNIN", quest = 777, questName = "This Is Going to Be Hard", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 34
        { type = "ACCEPT", quest = 778, questName = "This Is Going to Be Hard", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 35
        { type = "KILL", quest = 778, questName = "This Is Going to Be Hard", npc = 2919, target = "Fam'retor Guardian", map = 1418, zone = "Badlands", x = 26, y = 45.8, note = "loot Lotwil's Shackles of Elemental Binding" }, -- 36
        { type = "TURNIN", quest = 778, questName = "This Is Going to Be Hard", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 37
        { type = "TURNIN", quest = 2202, questName = "Uldaman Reagent Run", npc = 6868, npcName = "Jarkal Mossmeld", map = 1418, zone = "Badlands", x = 2.4, y = 46.1 }, -- 38
        { type = "COLLECT", quest = 2418, questName = "Power Stones", target = "Dentrium Power Stone / An'Alleum Power Stone", map = 1418, zone = "Badlands", x = 51.2, y = 27.2 }, -- 39
        { type = "TURNIN", quest = 2418, questName = "Power Stones", npc = 2817, npcName = "Rigglefuzz", map = 1418, zone = "Badlands", x = 42.4, y = 52.9 }, -- 40
        { type = "TURNIN", quest = 1420, questName = "Report to Helgrum", npc = 1442, npcName = "Helgrum the Swift", map = 1435, zone = "Swamp of Sorrows", x = 47.7, y = 55.2 }, -- 41
        { type = "GRIND", level = 40, note = "the next quests need level 40" }, -- 42
        { type = "ACCEPT", quest = 782, questName = "Broken Alliances", npc = 1068, npcName = "Gorn", map = 1418, zone = "Badlands", x = 2.9, y = 45.6 }, -- 43
        { type = "KILL", quest = 782, questName = "Broken Alliances", npc = 2944, target = "Boss Tho'grun", map = 1418, zone = "Badlands", x = 12.6, y = 75.5, note = "loot Sign of the Earth" }, -- 44
        { type = "TURNIN", quest = 782, questName = "Broken Alliances", npc = 1068, npcName = "Gorn", map = 1418, zone = "Badlands", x = 2.9, y = 45.6 }, -- 45
        { type = "ACCEPT", quest = 793, questName = "Broken Alliances", npc = 1068, npcName = "Gorn", map = 1418, zone = "Badlands", x = 2.9, y = 45.6 }, -- 46
        { type = "KILL", quest = 793, questName = "Broken Alliances", npc = 2757, target = "Blacklash / Hematus", map = 1418, zone = "Badlands", x = 81.9, y = 49.5, note = "loot Blacklash's Bindings" }, -- 47
        { type = "TURNIN", quest = 793, questName = "Broken Alliances", npc = 1068, npcName = "Gorn", map = 1418, zone = "Badlands", x = 2.9, y = 45.6 }, -- 48
    },
})
