-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_BADLANDS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_BADLANDS",
    name = "Badlands 35-45 (Alliance)",
    version = 1,
    faction = "Alliance",
    minLevel = 35,
    maxLevel = 45,
    next = "GEN_ALLIANCE_TANARIS",
    author = "ForeverGuide route generator",
    notes = "Auto-generated from the quest database: 19 quests, 51 steps, model reaches level 40. Not a speedrun route - a sensible order; the engine adapts as you play.",
    steps = {
        { type = "ACCEPT", quest = 2418, questName = "Power Stones", npc = 2817, npcName = "Rigglefuzz", map = 1418, zone = "Badlands", x = 42.4, y = 52.9 }, -- 1
        { type = "ACCEPT", quest = 703, questName = "Barbecued Buzzard Wings", npc = 2817, npcName = "Rigglefuzz", map = 1418, zone = "Badlands", x = 42.4, y = 52.9 }, -- 2
        { type = "COLLECT", quest = 703, questName = "Barbecued Buzzard Wings", target = "Buzzard Wing", map = 1418, zone = "Badlands", x = 48.6, y = 55.5, near = true }, -- 3
        { type = "TURNIN", quest = 703, questName = "Barbecued Buzzard Wings", npc = 2817, npcName = "Rigglefuzz", map = 1418, zone = "Badlands", x = 42.4, y = 52.9 }, -- 4
        { type = "ACCEPT", quest = 719, questName = "A Dwarf and His Tools", npc = 2910, npcName = "Prospector Ryedol", map = 1418, zone = "Badlands", x = 53.4, y = 43.4 }, -- 5
        { type = "ACCEPT", quest = 718, questName = "Mirages", npc = 2860, npcName = "Sigrun Ironhew", map = 1418, zone = "Badlands", x = 53.8, y = 43.3 }, -- 6
        { type = "COLLECT", quest = 719, questName = "A Dwarf and His Tools", target = "Ryedol's Lucky Pick", map = 1418, zone = "Badlands", x = 52.9, y = 34.4, near = true }, -- 7
        { type = "ACCEPT", quest = 720, questName = "A Sign of Hope", map = 1418, zone = "Badlands", x = 53, y = 33.9 }, -- 8
        { type = "COLLECT", quest = 2418, questName = "Power Stones", target = "Dentrium Power Stone / An'Alleum Power Stone", map = 1418, zone = "Badlands", x = 52.2, y = 27.6, near = true }, -- 9
        { type = "COLLECT", quest = 718, questName = "Mirages", target = "Supply Crate", map = 1418, zone = "Badlands", x = 66.6, y = 22 }, -- 10
        { type = "TURNIN", quest = 719, questName = "A Dwarf and His Tools", npc = 2910, npcName = "Prospector Ryedol", map = 1418, zone = "Badlands", x = 53.4, y = 43.4 }, -- 11
        { type = "TURNIN", quest = 720, questName = "A Sign of Hope", npc = 2910, npcName = "Prospector Ryedol", map = 1418, zone = "Badlands", x = 53.4, y = 43.4 }, -- 12
        { type = "TURNIN", quest = 718, questName = "Mirages", npc = 2860, npcName = "Sigrun Ironhew", map = 1418, zone = "Badlands", x = 53.8, y = 43.3 }, -- 13
        { type = "ACCEPT", quest = 721, questName = "A Sign of Hope", npc = 2910, npcName = "Prospector Ryedol", map = 1418, zone = "Badlands", x = 53.4, y = 43.4 }, -- 14
        { type = "ACCEPT", quest = 733, questName = "Scrounging", npc = 2860, npcName = "Sigrun Ironhew", map = 1418, zone = "Badlands", x = 53.8, y = 43.3 }, -- 15
        { type = "COLLECT", quest = 733, questName = "Scrounging", target = "Scrap Metal", map = 1418, zone = "Badlands", x = 64.7, y = 25.6, near = true }, -- 16
        { type = "TURNIN", quest = 733, questName = "Scrounging", npc = 2860, npcName = "Sigrun Ironhew", map = 1418, zone = "Badlands", x = 53.8, y = 43.3 }, -- 17
        { type = "TURNIN", quest = 2418, questName = "Power Stones", npc = 2817, npcName = "Rigglefuzz", map = 1418, zone = "Badlands", x = 42.4, y = 52.9 }, -- 18
        { type = "ACCEPT", quest = 710, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 19
        { type = "ACCEPT", quest = 713, questName = "Coolant Heads Prevail", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 20
        { type = "TURNIN", quest = 713, questName = "Coolant Heads Prevail", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 21
        { type = "ACCEPT", quest = 714, questName = "Gyro... What?", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 22
        { type = "TURNIN", quest = 714, questName = "Gyro... What?", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 23
        { type = "KILL", quest = 710, questName = "Study of the Elements: Rock", npc = 2735, target = "Lesser Rock Elemental", map = 1418, zone = "Badlands", x = 23.5, y = 45.5, near = true, note = "loot Small Stone Shard" }, -- 24
        { type = "TURNIN", quest = 710, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 25
        { type = "ACCEPT", quest = 711, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 26
        { type = "KILL", quest = 711, questName = "Study of the Elements: Rock", npc = 92, target = "Rock Elemental", map = 1418, zone = "Badlands", x = 13.4, y = 33.4, near = true, note = "loot Large Stone Slab" }, -- 27
        { type = "TURNIN", quest = 711, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 28
        { type = "ACCEPT", quest = 712, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 29
        { type = "KILL", quest = 712, questName = "Study of the Elements: Rock", npc = 2736, target = "Greater Rock Elemental", map = 1418, zone = "Badlands", x = 6.6, y = 76.3, near = true, note = "loot Bracers of Rock Binding" }, -- 30
        { type = "TURNIN", quest = 712, questName = "Study of the Elements: Rock", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 31
        { type = "ACCEPT", quest = 734, questName = "This Is Going to Be Hard", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 32
        { type = "ACCEPT", quest = 716, questName = "Stone Is Better than Cloth", npc = 2920, npcName = "Lucien Tosselwrench", map = 1418, zone = "Badlands", x = 25.8, y = 44.2 }, -- 33
        { type = "TURNIN", quest = 716, questName = "Stone Is Better than Cloth", npc = 2920, npcName = "Lucien Tosselwrench", map = 1418, zone = "Badlands", x = 25.8, y = 44.2 }, -- 34
        { type = "TURNIN", quest = 734, questName = "This Is Going to Be Hard", npc = 2920, npcName = "Lucien Tosselwrench", map = 1418, zone = "Badlands", x = 25.8, y = 44.2 }, -- 35
        { type = "ACCEPT", quest = 777, questName = "This Is Going to Be Hard", npc = 2920, npcName = "Lucien Tosselwrench", map = 1418, zone = "Badlands", x = 25.8, y = 44.2 }, -- 36
        { type = "TURNIN", quest = 777, questName = "This Is Going to Be Hard", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 37
        { type = "ACCEPT", quest = 778, questName = "This Is Going to Be Hard", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 38
        { type = "KILL", quest = 778, questName = "This Is Going to Be Hard", npc = 2919, target = "Fam'retor Guardian", map = 1418, zone = "Badlands", x = 26, y = 45.8, note = "loot Lotwil's Shackles of Elemental Binding" }, -- 39
        { type = "TURNIN", quest = 778, questName = "This Is Going to Be Hard", npc = 2921, npcName = "Lotwil Veriatus", map = 1418, zone = "Badlands", x = 26, y = 44.9 }, -- 40
        { type = "TURNIN", quest = 721, questName = "A Sign of Hope", npc = 2909, npcName = "Hammertoe Grez", map = 1432, zone = "Loch Modan", x = 37.3, y = 85.8 }, -- 41
        { type = "GRIND", level = 40, note = "the next quests need level 40" }, -- 42
        { type = "ACCEPT", quest = 706, questName = "Fiery Blaze Enchantments", npc = 2860, npcName = "Sigrun Ironhew", map = 1418, zone = "Badlands", x = 53.8, y = 43.3 }, -- 43
        { type = "COLLECT", quest = 706, questName = "Fiery Blaze Enchantments", target = "Black Drake's Heart", map = 1418, zone = "Badlands", x = 69.7, y = 53.8, near = true }, -- 44
        { type = "TURNIN", quest = 706, questName = "Fiery Blaze Enchantments", npc = 2860, npcName = "Sigrun Ironhew", map = 1418, zone = "Badlands", x = 53.8, y = 43.3 }, -- 45
        { type = "ACCEPT", quest = 732, questName = "Tremors of the Earth", npc = 2888, npcName = "Garek", map = 1418, zone = "Badlands", x = 61.9, y = 54.3 }, -- 46
        { type = "KILL", quest = 732, questName = "Tremors of the Earth", npc = 2944, target = "Boss Tho'grun", map = 1418, zone = "Badlands", x = 12.6, y = 75.5, note = "loot Sign of the Earth" }, -- 47
        { type = "TURNIN", quest = 732, questName = "Tremors of the Earth", npc = 2888, npcName = "Garek", map = 1418, zone = "Badlands", x = 61.9, y = 54.3 }, -- 48
        { type = "ACCEPT", quest = 717, questName = "Tremors of the Earth", npc = 2888, npcName = "Garek", map = 1418, zone = "Badlands", x = 61.9, y = 54.3, optional = true, note = "elite target - bring a group (optional)" }, -- 49
        { type = "KILL", quest = 717, questName = "Tremors of the Earth", npc = 2757, target = "Blacklash / Hematus", map = 1418, zone = "Badlands", x = 81.9, y = 49.5, optional = true, note = "ELITE - loot Blacklash's Bindings (group quest, optional)" }, -- 50
        { type = "TURNIN", quest = 717, questName = "Tremors of the Earth", npc = 2888, npcName = "Garek", map = 1418, zone = "Badlands", x = 61.9, y = 54.3, optional = true }, -- 51
    },
})
