-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_SCOURGE_29_UNDERCITY.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_SCOURGE_29_UNDERCITY",
    name = "29. Undercity 49-49 (Undead)",
    version = 2,
    faction = "Horde",
    race = { "Scourge" },
    minLevel = 49,
    maxLevel = 49,
    map = 1458,
    zone = "Undercity",
    next = "GEN_HORDE_SCOURGE_30_THE_HINTERLANDS",
    author = "ForeverGuide route planner",
    notes = "Chapter 29 of the Scourge route: level 49 to 49, 17 steps, ~21 min of play in the model (55603 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1458, zone = "Undercity", x = 59.6, y = 64.6, radius = 60, note = "travel to Undercity (Undercity)" }, -- 1
        { type = "ACCEPT", quest = 1109, questName = "Going, Going, Guano!", npc = 2055, npcName = "Master Apothecary Faranell", map = 1458, zone = "Undercity", x = 48.8, y = 69.3 }, -- 2
        { type = "ACCEPT", quest = 232, questName = "Errand for Apothecary Zinge", npc = 5204, npcName = "Apothecary Zinge", map = 1458, zone = "Undercity", x = 50.1, y = 68 }, -- 3
        { type = "ACCEPT", quest = 4293, questName = "A Sample of Slime...", npc = 10136, npcName = "Chemist Fuely", map = 1458, zone = "Undercity", x = 47.5, y = 73.4 }, -- 4
        { type = "ACCEPT", quest = 4294, questName = "... and a Batch of Ooze", npc = 10136, npcName = "Chemist Fuely", map = 1458, zone = "Undercity", x = 47.5, y = 73.4 }, -- 5
        { type = "TURNIN", quest = 513, questName = "Elixir of Agony", npc = 2055, npcName = "Master Apothecary Faranell", map = 1458, zone = "Undercity", x = 48.8, y = 69.3, note = "reduced xp (10%) - you out-levelled it" }, -- 6
        { type = "TURNIN", quest = 1109, questName = "Going, Going, Guano!", npc = 2055, npcName = "Master Apothecary Faranell", map = 1458, zone = "Undercity", x = 48.8, y = 69.3, note = "reduced xp (10%) - you out-levelled it" }, -- 7
        { type = "TURNIN", quest = 232, questName = "Errand for Apothecary Zinge", npc = 7683, npcName = "Alessandro Luca", map = 1458, zone = "Undercity", x = 58.6, y = 54.7 }, -- 8
        { type = "ACCEPT", quest = 238, questName = "Errand for Apothecary Zinge", npc = 7683, npcName = "Alessandro Luca", map = 1458, zone = "Undercity", x = 58.6, y = 54.7 }, -- 9
        { type = "TURNIN", quest = 238, questName = "Errand for Apothecary Zinge", npc = 5204, npcName = "Apothecary Zinge", map = 1458, zone = "Undercity", x = 50.1, y = 68 }, -- 10
        { type = "TURNIN", quest = 5023, questName = "Better Late Than Never", npc = 10781, npcName = "Royal Overseer Bauhaus", map = 1458, zone = "Undercity", x = 69.8, y = 43.2 }, -- 11
        { type = "ACCEPT", quest = 5049, questName = "The Jeremiah Blues", npc = 10781, npcName = "Royal Overseer Bauhaus", map = 1458, zone = "Undercity", x = 69.8, y = 43.2 }, -- 12
        { type = "TURNIN", quest = 5049, questName = "The Jeremiah Blues", npc = 8403, npcName = "Jeremiah Payson", map = 1458, zone = "Undercity", x = 67.6, y = 44.2 }, -- 13
        { type = "COLLECT", quest = 4293, questName = "A Sample of Slime...", target = "Corrupted Felwood Sample", count = 5, map = 1458, zone = "Undercity", x = 47.9, y = 73.5 }, -- 14
        { type = "TURNIN", quest = 4293, questName = "A Sample of Slime...", npc = 10136, npcName = "Chemist Fuely", map = 1458, zone = "Undercity", x = 47.5, y = 73.4 }, -- 15
        { type = "COLLECT", quest = 4294, questName = "... and a Batch of Ooze", target = "Pure Un'Goro Sample", count = 5, map = 1458, zone = "Undercity", x = 47.7, y = 73.6 }, -- 16
        { type = "TURNIN", quest = 4294, questName = "... and a Batch of Ooze", npc = 10136, npcName = "Chemist Fuely", map = 1458, zone = "Undercity", x = 47.5, y = 73.4 }, -- 17
    },
})
