-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_AZSHARA.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_AZSHARA",
    name = "Azshara 45-55 (Horde)",
    version = 1,
    faction = "Horde",
    minLevel = 45,
    maxLevel = 55,
    map = 1447,
    zone = "Azshara",
    next = "GEN_HORDE_FELWOOD",
    author = "ForeverGuide route generator",
    notes = "Auto-generated from the quest database: 10 quests, 27 steps, model reaches level 47. Not a speedrun route - a sensible order; the engine adapts as you play.",
    steps = {
        { type = "ACCEPT", quest = 3517, questName = "Stealing Knowledge", npc = 8587, npcName = "Jediga", map = 1447, zone = "Azshara", x = 22.6, y = 51.4 }, -- 1
        { type = "COLLECT", quest = 3517, questName = "Stealing Knowledge", target = "Tablet of Beth'Amara / Tablet of Jin'yael", map = 1447, zone = "Azshara", x = 34.1, y = 50.5, near = true }, -- 2
        { type = "COLLECT", quest = 3517, questName = "Stealing Knowledge", target = "Tablet of Markri / Tablet of Sael'hai", map = 1447, zone = "Azshara", x = 36.2, y = 52.6, near = true }, -- 3
        { type = "TURNIN", quest = 3517, questName = "Stealing Knowledge", npc = 8587, npcName = "Jediga", map = 1447, zone = "Azshara", x = 22.6, y = 51.4 }, -- 4
        { type = "ACCEPT", quest = 3518, questName = "Delivery to Magatha", npc = 8587, npcName = "Jediga", map = 1447, zone = "Azshara", x = 22.6, y = 51.4 }, -- 5
        { type = "ACCEPT", quest = 3541, questName = "Delivery to Jes'rimon", npc = 8587, npcName = "Jediga", map = 1447, zone = "Azshara", x = 22.6, y = 51.4 }, -- 6
        { type = "ACCEPT", quest = 3542, questName = "Delivery to Andron Gant", npc = 8587, npcName = "Jediga", map = 1447, zone = "Azshara", x = 22.6, y = 51.4 }, -- 7
        { type = "ACCEPT", quest = 3561, questName = "Delivery to Archmage Xylem", npc = 8587, npcName = "Jediga", map = 1447, zone = "Azshara", x = 22.6, y = 51.4 }, -- 8
        { type = "TURNIN", quest = 3561, questName = "Delivery to Archmage Xylem", npc = 8379, npcName = "Archmage Xylem", map = 1447, zone = "Azshara", x = 29.3, y = 40.2 }, -- 9
        { type = "ACCEPT", quest = 3565, questName = "Xylem's Payment to Jediga", npc = 8379, npcName = "Archmage Xylem", map = 1447, zone = "Azshara", x = 29.3, y = 40.2 }, -- 10
        { type = "TURNIN", quest = 3565, questName = "Xylem's Payment to Jediga", npc = 8587, npcName = "Jediga", map = 1447, zone = "Azshara", x = 22.6, y = 51.4 }, -- 11
        { type = "ACCEPT", quest = 5535, questName = "Spiritual Unrest", npc = 11548, npcName = "Loh'atu", map = 1447, zone = "Azshara", x = 11.4, y = 78.2 }, -- 12
        { type = "ACCEPT", quest = 5536, questName = "A Land Filled with Hatred", npc = 11548, npcName = "Loh'atu", map = 1447, zone = "Azshara", x = 11.4, y = 78.2 }, -- 13
        { type = "KILL", quest = 5535, questName = "Spiritual Unrest", npc = 6117, target = "Highborne Lichling / Highborne Apparition", map = 1447, zone = "Azshara", x = 13.5, y = 73.2, near = true }, -- 14
        { type = "KILL", quest = 5536, questName = "A Land Filled with Hatred", npc = 6127, target = "Haldarr Felsworn / Haldarr Trickster / Haldarr Satyr", map = 1447, zone = "Azshara", x = 19.1, y = 64, near = true }, -- 15
        { type = "TURNIN", quest = 5535, questName = "Spiritual Unrest", npc = 11548, npcName = "Loh'atu", map = 1447, zone = "Azshara", x = 11.4, y = 78.2 }, -- 16
        { type = "TURNIN", quest = 5536, questName = "A Land Filled with Hatred", npc = 11548, npcName = "Loh'atu", map = 1447, zone = "Azshara", x = 11.4, y = 78.2 }, -- 17
        { type = "TURNIN", quest = 3542, questName = "Delivery to Andron Gant", npc = 6522, npcName = "Andron Gant", map = 1458, zone = "Undercity", x = 54.8, y = 76.3 }, -- 18
        { type = "TURNIN", quest = 3541, questName = "Delivery to Jes'rimon", npc = 8659, npcName = "Jes'rimon", map = 1454, zone = "Orgrimmar", x = 55.5, y = 34.1 }, -- 19
        { type = "TURNIN", quest = 3518, questName = "Delivery to Magatha", npc = 4046, npcName = "Magatha Grimtotem", map = 1456, zone = "Thunder Bluff", x = 69.9, y = 30.9 }, -- 20
        { type = "GRIND", level = 47, note = "the next quests need level 47" }, -- 21
        { type = "ACCEPT", quest = 3601, questName = "Kim'jael Indeed!", npc = 8420, npcName = "Kim'jael", map = 1447, zone = "Azshara", x = 53.5, y = 21.8 }, -- 22
        { type = "COLLECT", quest = 3601, questName = "Kim'jael Indeed!", target = "Kim'Jael's Compass / Kim'Jael's Scope / Kim'Jael's Stuffed Chicken / Kim'Jael's Wizzlegoober", map = 1447, zone = "Azshara", x = 59.2, y = 23, near = true }, -- 23
        { type = "TURNIN", quest = 3601, questName = "Kim'jael Indeed!", npc = 8420, npcName = "Kim'jael", map = 1447, zone = "Azshara", x = 53.5, y = 21.8 }, -- 24
        { type = "ACCEPT", quest = 5534, questName = "Kim'jael's \"Missing\" Equipment", npc = 8420, npcName = "Kim'jael", map = 1447, zone = "Azshara", x = 53.5, y = 21.8 }, -- 25
        { type = "COLLECT", quest = 5534, questName = "Kim'jael's \"Missing\" Equipment", target = "Some Rune", map = 1447, zone = "Azshara", x = 49.5, y = 42, near = true }, -- 26
        { type = "TURNIN", quest = 5534, questName = "Kim'jael's \"Missing\" Equipment", npc = 8420, npcName = "Kim'jael", map = 1447, zone = "Azshara", x = 53.5, y = 21.8 }, -- 27
    },
})
