-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_DWARF_07_STORMWIND_CITY.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_DWARF_07_STORMWIND_CITY",
    name = "7. Stormwind City 21-21 (Dwarf)",
    version = 2,
    faction = "Alliance",
    race = { "Dwarf", "Gnome" },
    minLevel = 21,
    maxLevel = 21,
    map = 1453,
    zone = "Stormwind City",
    next = "GEN_ALLIANCE_DWARF_08_WETLANDS",
    author = "ForeverGuide route planner",
    notes = "Chapter 7 of the Dwarf route: level 21 to 21, 8 steps, ~12 min of play in the model (26868 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1453, zone = "Stormwind City", x = 75.1, y = 30.6, radius = 60, note = "travel to Stormwind City (Stormwind City)" }, -- 1
        { type = "NOTE", map = 1453, zone = "Stormwind City", x = 75.1, y = 30.6, text = "set your hearthstone at the inn in Stormwind City (if there is one)" }, -- 2
        { type = "ACCEPT", quest = 8374, questName = "Claiming Arathi Basin", npc = 15351, npcName = "Alliance Brigadier General", map = 1453, zone = "Stormwind City", x = 79.6, y = 18.2 }, -- 3
        { type = "TURNIN", quest = 8374, questName = "Claiming Arathi Basin", npc = 15351, npcName = "Alliance Brigadier General", map = 1453, zone = "Stormwind City", x = 79.6, y = 18.2 }, -- 4
        { type = "ACCEPT", quest = 388, questName = "The Color of Blood", npc = 1721, npcName = "Nikova Raskol", map = 1453, zone = "Stormwind City", x = 73.3, y = 50.7 }, -- 5
        { type = "TURNIN", quest = 388, questName = "The Color of Blood", npc = 1721, npcName = "Nikova Raskol", map = 1453, zone = "Stormwind City", x = 73.3, y = 50.7 }, -- 6
        { type = "ACCEPT", quest = 343, questName = "Speaking of Fortitude", npc = 1444, npcName = "Brother Kristoff", map = 1453, zone = "Stormwind City", x = 45.7, y = 38.4 }, -- 7
        { type = "TURNIN", quest = 343, questName = "Speaking of Fortitude", npc = 1440, npcName = "Milton Sheaf", map = 1453, zone = "Stormwind City", x = 74.2, y = 7.5 }, -- 8
    },
})
