-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_HUMAN_46_BURNING_STEPPES.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_HUMAN_46_BURNING_STEPPES",
    name = "46. Burning Steppes 55-55 (Human)",
    version = 2,
    faction = "Alliance",
    race = { "Human" },
    minLevel = 55,
    maxLevel = 55,
    map = 1428,
    zone = "Burning Steppes",
    next = "GEN_ALLIANCE_HUMAN_47_WINTERSPRING",
    author = "ForeverGuide route planner",
    notes = "Chapter 46 of the Human route: level 55 to 55, 10 steps, ~31 min of play in the model (56710 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1428, zone = "Burning Steppes", x = 65.4, y = 23.3, radius = 60, note = "travel to Burning Steppes (Burning Steppes)" }, -- 1
        { type = "ACCEPT", quest = 4729, questName = "Kibler's Exotic Pets", npc = 10260, npcName = "Kibler", map = 1428, zone = "Burning Steppes", x = 65.9, y = 21.9 }, -- 2
        { type = "ACCEPT", quest = 4862, questName = "En-Ay-Es-Tee-Why", npc = 10260, npcName = "Kibler", map = 1428, zone = "Burning Steppes", x = 65.9, y = 21.9 }, -- 3
        { type = "ACCEPT", quest = 4866, questName = "Mother's Milk", npc = 9563, npcName = "Ragged John", map = 1428, zone = "Burning Steppes", x = 65, y = 23.8 }, -- 4
        { type = "TURNIN", quest = 4729, questName = "Kibler's Exotic Pets", npc = 10260, npcName = "Kibler", map = 1428, zone = "Burning Steppes", x = 65.9, y = 21.9 }, -- 5
        { type = "TURNIN", quest = 4862, questName = "En-Ay-Es-Tee-Why", npc = 10260, npcName = "Kibler", map = 1428, zone = "Burning Steppes", x = 65.9, y = 21.9 }, -- 6
        { type = "KILL", quest = 4866, questName = "Mother's Milk", npc = 9563, target = "Ragged John", count = 1, map = 1428, zone = "Burning Steppes", x = 65, y = 23.8 }, -- 7
        { type = "TURNIN", quest = 4866, questName = "Mother's Milk", npc = 9563, npcName = "Ragged John", map = 1428, zone = "Burning Steppes", x = 65, y = 23.8 }, -- 8
        { type = "ACCEPT", quest = 7848, questName = "Attunement to the Core", npc = 14387, npcName = "Lothos Riftwaker", map = 1428, zone = "Burning Steppes", x = 26.4, y = 24.5 }, -- 9
        { type = "TURNIN", quest = 7848, questName = "Attunement to the Core", npc = 14387, npcName = "Lothos Riftwaker", map = 1428, zone = "Burning Steppes", x = 26.4, y = 24.5 }, -- 10
    },
})
