-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ZONE_ALLIANCE_UN_GORO_CRATER.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ZONE_ALLIANCE_UN_GORO_CRATER",
    name = "Zone: Un'Goro Crater 48-55 (Alliance)",
    version = 2,
    faction = "Alliance",
    minLevel = 48,
    maxLevel = 55,
    map = 1449,
    zone = "Un'Goro Crater",
    author = "ForeverGuide route planner",
    notes = "Every quest worth doing in Un'Goro Crater for a Alliance character, 22 quests. The race routes are the faster path; pick this when you just want to quest here.",
    stepCount = 69,
    steps = function() return {
        { type = "TRAVEL", map = 1449, zone = "Un'Goro Crater", x = 43.2, y = 6.6, radius = 60, note = "travel to Un'Goro Crater (Un'Goro Crater)" }, -- 1
        { type = "NOTE", map = 1449, zone = "Un'Goro Crater", x = 43.2, y = 6.6, text = "set your hearthstone at the inn in Un'Goro Crater (if there is one)" }, -- 2
        { type = "ACCEPT", quest = 3883, questName = "Alien Ecology", npc = 9271, npcName = "Hol'anyee Marshal", map = 1449, zone = "Un'Goro Crater", x = 43.9, y = 7.2 }, -- 3
        { type = "ACCEPT", quest = 4141, questName = "Muigin and Larion", npc = 9119, npcName = "Muigin", map = 1449, zone = "Un'Goro Crater", x = 42.9, y = 9.6 }, -- 4
        { type = "ACCEPT", quest = 3881, questName = "Expedition Salvation", npc = 9270, npcName = "Williden Marshal", map = 1449, zone = "Un'Goro Crater", x = 44, y = 7.1 }, -- 5
        { type = "ACCEPT", quest = 4284, questName = "Crystals of Power", npc = 9117, npcName = "J.D. Collie", map = 1449, zone = "Un'Goro Crater", x = 41.9, y = 2.7 }, -- 6
        { type = "ACCEPT", quest = 4243, questName = "Chasing A-Me 01", npc = 9618, npcName = "Karna Remtravel", map = 1449, zone = "Un'Goro Crater", x = 46.4, y = 13.4 }, -- 7
        { type = "COLLECT", quest = 4141, questName = "Muigin and Larion", target = "Bloodpetal", count = 15, map = 1449, zone = "Un'Goro Crater", x = 40.3, y = 23.3, near = true }, -- 8
        { type = "COLLECT", quest = 4284, questName = "Crystals of Power", target = "Red Power Crystal / Yellow Power Crystal / Green Power Crystal / Blue Power Crystal", count = 7, map = 1449, zone = "Un'Goro Crater", x = 43, y = 45.4, near = true }, -- 9
        { type = "COLLECT", quest = 3881, questName = "Expedition Salvation", target = "Research Equipment", map = 1449, zone = "Un'Goro Crater", x = 38.5, y = 66.1 }, -- 10
        { type = "COLLECT", quest = 3883, questName = "Alien Ecology", target = "Hive Wall Sample", map = 1449, zone = "Un'Goro Crater", x = 48.7, y = 85.3 }, -- 11
        { type = "COLLECT", quest = 3881, questName = "Expedition Salvation", target = "Crate of Foodstuffs", map = 1449, zone = "Un'Goro Crater", x = 68.5, y = 36.5 }, -- 12
        { type = "TURNIN", quest = 4141, questName = "Muigin and Larion", npc = 9119, npcName = "Muigin", map = 1449, zone = "Un'Goro Crater", x = 42.9, y = 9.6 }, -- 13
        { type = "ACCEPT", quest = 4142, questName = "A Visit to Gregan", npc = 9119, npcName = "Muigin", map = 1449, zone = "Un'Goro Crater", x = 42.9, y = 9.6 }, -- 14
        { type = "TURNIN", quest = 3883, questName = "Alien Ecology", npc = 9271, npcName = "Hol'anyee Marshal", map = 1449, zone = "Un'Goro Crater", x = 43.9, y = 7.2 }, -- 15
        { type = "TURNIN", quest = 3881, questName = "Expedition Salvation", npc = 9270, npcName = "Williden Marshal", map = 1449, zone = "Un'Goro Crater", x = 44, y = 7.1 }, -- 16
        { type = "TURNIN", quest = 4284, questName = "Crystals of Power", npc = 9117, npcName = "J.D. Collie", map = 1449, zone = "Un'Goro Crater", x = 41.9, y = 2.7 }, -- 17
        { type = "ACCEPT", quest = 4285, questName = "The Northern Pylon", npc = 9117, npcName = "J.D. Collie", map = 1449, zone = "Un'Goro Crater", x = 41.9, y = 2.7 }, -- 18
        { type = "ACCEPT", quest = 4287, questName = "The Eastern Pylon", npc = 9117, npcName = "J.D. Collie", map = 1449, zone = "Un'Goro Crater", x = 41.9, y = 2.7 }, -- 19
        { type = "ACCEPT", quest = 4288, questName = "The Western Pylon", npc = 9117, npcName = "J.D. Collie", map = 1449, zone = "Un'Goro Crater", x = 41.9, y = 2.7 }, -- 20
        { type = "COMPLETE", quest = 4285, questName = "The Northern Pylon", target = "Discover and examine the Northern Crystal Pylon", map = 1449, zone = "Un'Goro Crater", x = 56, y = 12, note = "Discover and examine the Northern Crystal Pylon" }, -- 21
        { type = "COMPLETE", quest = 4287, questName = "The Eastern Pylon", target = "Discover and examine the Eastern Crystal Pylon", map = 1449, zone = "Un'Goro Crater", x = 77, y = 50, note = "Discover and examine the Eastern Crystal Pylon" }, -- 22
        { type = "COMPLETE", quest = 4288, questName = "The Western Pylon", target = "Discover and examine the Western Crystal Pylon", map = 1449, zone = "Un'Goro Crater", x = 23, y = 59, note = "Discover and examine the Western Crystal Pylon" }, -- 23
        { type = "TURNIN", quest = 4285, questName = "The Northern Pylon", npc = 9117, npcName = "J.D. Collie", map = 1449, zone = "Un'Goro Crater", x = 41.9, y = 2.7 }, -- 24
        { type = "TURNIN", quest = 4287, questName = "The Eastern Pylon", npc = 9117, npcName = "J.D. Collie", map = 1449, zone = "Un'Goro Crater", x = 41.9, y = 2.7 }, -- 25
        { type = "TURNIN", quest = 4288, questName = "The Western Pylon", npc = 9117, npcName = "J.D. Collie", map = 1449, zone = "Un'Goro Crater", x = 41.9, y = 2.7 }, -- 26
        { type = "ACCEPT", quest = 4321, questName = "Making Sense of It", npc = 9117, npcName = "J.D. Collie", map = 1449, zone = "Un'Goro Crater", x = 41.9, y = 2.7 }, -- 27
        { type = "TURNIN", quest = 4321, questName = "Making Sense of It", npc = 9117, npcName = "J.D. Collie", map = 1449, zone = "Un'Goro Crater", x = 41.9, y = 2.7 }, -- 28
        { type = "TURNIN", quest = 4243, questName = "Chasing A-Me 01", npc = 9623, npcName = "A-Me 01", map = 1449, zone = "Un'Goro Crater", x = 67.7, y = 16.8 }, -- 29
        { type = "ACCEPT", quest = 3844, questName = "It's a Secret to Everybody", map = 1449, zone = "Un'Goro Crater", x = 63, y = 68.6 }, -- 30
        { type = "TURNIN", quest = 3844, questName = "It's a Secret to Everybody", map = 1449, zone = "Un'Goro Crater", x = 63.1, y = 69.1 }, -- 31
        { type = "ACCEPT", quest = 3845, questName = "It's a Secret to Everybody", map = 1449, zone = "Un'Goro Crater", x = 63.1, y = 69.1 }, -- 32
        { type = "ACCEPT", quest = 4289, questName = "The Apes of Un'Goro", npc = 9619, npcName = "Torwa Pathfinder", map = 1449, zone = "Un'Goro Crater", x = 71.6, y = 76 }, -- 33
        { type = "ACCEPT", quest = 4290, questName = "The Fare of Lar'korwi", npc = 9619, npcName = "Torwa Pathfinder", map = 1449, zone = "Un'Goro Crater", x = 71.6, y = 76 }, -- 34
        { type = "COLLECT", quest = 4290, questName = "The Fare of Lar'korwi", target = "Piece of Threshadon Carcass", map = 1449, zone = "Un'Goro Crater", x = 68.7, y = 56.7 }, -- 35
        { type = "KILL", quest = 4289, questName = "The Apes of Un'Goro", npc = 6514, target = "Un'Goro Gorilla / Un'Goro Stomper / Un'Goro Thunderer", count = 2, map = 1449, zone = "Un'Goro Crater", x = 62.6, y = 19.7, near = true, note = "loot Un'Goro Gorilla Pelt" }, -- 36
        { type = "TURNIN", quest = 4289, questName = "The Apes of Un'Goro", npc = 9619, npcName = "Torwa Pathfinder", map = 1449, zone = "Un'Goro Crater", x = 71.6, y = 76 }, -- 37
        { type = "TURNIN", quest = 4290, questName = "The Fare of Lar'korwi", npc = 9619, npcName = "Torwa Pathfinder", map = 1449, zone = "Un'Goro Crater", x = 71.6, y = 76 }, -- 38
        { type = "ACCEPT", quest = 4291, questName = "The Scent of Lar'korwi", npc = 9619, npcName = "Torwa Pathfinder", map = 1449, zone = "Un'Goro Crater", x = 71.6, y = 76 }, -- 39
        { type = "KILL", quest = 4291, questName = "The Scent of Lar'korwi", npc = 9683, target = "Lar'korwi Mate", count = 2, map = 1449, zone = "Un'Goro Crater", x = 67, y = 73, near = true, note = "loot Ravasaur Pheromone Gland" }, -- 40
        { type = "TURNIN", quest = 4291, questName = "The Scent of Lar'korwi", npc = 9619, npcName = "Torwa Pathfinder", map = 1449, zone = "Un'Goro Crater", x = 71.6, y = 76 }, -- 41
        { type = "ACCEPT", quest = 4292, questName = "The Bait for Lar'korwi", npc = 9619, npcName = "Torwa Pathfinder", map = 1449, zone = "Un'Goro Crater", x = 71.6, y = 76 }, -- 42
        { type = "KILL", quest = 4292, questName = "The Bait for Lar'korwi", npc = 9684, target = "Lar'korwi", map = 1449, zone = "Un'Goro Crater", x = 79.7, y = 49.8, note = "loot Lar'korwi's Head" }, -- 43
        { type = "TURNIN", quest = 4292, questName = "The Bait for Lar'korwi", npc = 9619, npcName = "Torwa Pathfinder", map = 1449, zone = "Un'Goro Crater", x = 71.6, y = 76 }, -- 44
        { type = "TURNIN", quest = 3845, questName = "It's a Secret to Everybody", npc = 8737, npcName = "Linken", map = 1449, zone = "Un'Goro Crater", x = 44.7, y = 8.1 }, -- 45
        { type = "ACCEPT", quest = 3882, questName = "Roll the Bones", npc = 9272, npcName = "Spark Nilminer", map = 1449, zone = "Un'Goro Crater", x = 43.5, y = 7.4 }, -- 46
        { type = "ACCEPT", quest = 4503, questName = "Shizzle's Flyer", npc = 9998, npcName = "Shizzle", map = 1449, zone = "Un'Goro Crater", x = 44.2, y = 11.6 }, -- 47
        { type = "ACCEPT", quest = 3908, questName = "It's a Secret to Everybody", npc = 8737, npcName = "Linken", map = 1449, zone = "Un'Goro Crater", x = 44.7, y = 8.1 }, -- 48
        { type = "ACCEPT", quest = 4501, questName = "Beware of Pterrordax", map = 1449, zone = "Un'Goro Crater", x = 43.5, y = 8.4 }, -- 49
        { type = "COLLECT", quest = 4503, questName = "Shizzle's Flyer", target = "Webbed Pterrordax Scale", count = 8, map = 1449, zone = "Un'Goro Crater", x = 50.6, y = 12, near = true }, -- 50
        { type = "KILL", quest = 4501, questName = "Beware of Pterrordax", npc = 9166, target = "Pterrordax", count = 10, map = 1449, zone = "Un'Goro Crater", x = 50.6, y = 12, near = true }, -- 51
        { type = "COLLECT", quest = 3882, questName = "Roll the Bones", target = "Dinosaur Bone", count = 8, map = 1449, zone = "Un'Goro Crater", x = 58.1, y = 33.9, near = true }, -- 52
        { type = "COLLECT", quest = 4503, questName = "Shizzle's Flyer", target = "Webbed Diemetradon Scale", count = 8, map = 1449, zone = "Un'Goro Crater", x = 58.1, y = 33.9, near = true }, -- 53
        { type = "KILL", quest = 4501, questName = "Beware of Pterrordax", npc = 9167, target = "Frenzied Pterrordax", count = 10, map = 1449, zone = "Un'Goro Crater", x = 37.4, y = 40.4, near = true }, -- 54
        { type = "TURNIN", quest = 4503, questName = "Shizzle's Flyer", npc = 9998, npcName = "Shizzle", map = 1449, zone = "Un'Goro Crater", x = 44.2, y = 11.6 }, -- 55
        { type = "TURNIN", quest = 4501, questName = "Beware of Pterrordax", npc = 9997, npcName = "Spraggle Frock", map = 1449, zone = "Un'Goro Crater", x = 43.6, y = 8.5 }, -- 56
        { type = "TURNIN", quest = 3882, questName = "Roll the Bones", npc = 9272, npcName = "Spark Nilminer", map = 1449, zone = "Un'Goro Crater", x = 43.5, y = 7.4 }, -- 57
        { type = "ACCEPT", quest = 4492, questName = "Lost!", npc = 9997, npcName = "Spraggle Frock", map = 1449, zone = "Un'Goro Crater", x = 43.6, y = 8.5 }, -- 58
        { type = "COMPLETE", quest = 4492, questName = "Lost!", target = "Escort Ringo to Spraggle Frock at Marshal's Refuge", map = 1449, zone = "Un'Goro Crater", x = 43.7, y = 8.3, note = "escort - stay close, it can fail: Escort Ringo to Spraggle Frock at Marshal's Refuge" }, -- 59
        { type = "TURNIN", quest = 4492, questName = "Lost!", npc = 9999, npcName = "Ringo", map = 1449, zone = "Un'Goro Crater", x = 51.9, y = 49.9 }, -- 60
        { type = "ACCEPT", quest = 4491, questName = "A Little Help From My Friends", npc = 9999, npcName = "Ringo", map = 1449, zone = "Un'Goro Crater", x = 51.9, y = 49.9 }, -- 61
        { type = "COMPLETE", quest = 4491, questName = "A Little Help From My Friends", target = "Escort Ringo to Spraggle Frock at Marshal's Refuge", map = 1449, zone = "Un'Goro Crater", x = 43.7, y = 8.3, note = "escort - stay close, it can fail: Escort Ringo to Spraggle Frock at Marshal's Refuge" }, -- 62
        { type = "TURNIN", quest = 4491, questName = "A Little Help From My Friends", npc = 9997, npcName = "Spraggle Frock", map = 1449, zone = "Un'Goro Crater", x = 43.6, y = 8.5 }, -- 63
        { type = "ACCEPT", quest = 4301, questName = "The Mighty U'cha", npc = 9619, npcName = "Torwa Pathfinder", map = 1449, zone = "Un'Goro Crater", x = 71.6, y = 76 }, -- 64
        { type = "KILL", quest = 4301, questName = "The Mighty U'cha", npc = 9622, target = "U'cha", map = 1449, zone = "Un'Goro Crater", x = 68.1, y = 12.6, note = "loot U'cha's Pelt" }, -- 65
        { type = "TURNIN", quest = 4301, questName = "The Mighty U'cha", npc = 9619, npcName = "Torwa Pathfinder", map = 1449, zone = "Un'Goro Crater", x = 71.6, y = 76 }, -- 66
        { type = "ACCEPT", quest = 974, questName = "Finding the Source", npc = 10302, npcName = "Krakle", map = 1449, zone = "Un'Goro Crater", x = 30.9, y = 50.4 }, -- 67
        { type = "KILL", quest = 974, questName = "Finding the Source", npc = 10541, target = "Krakle's Thermometer", count = 1, map = 1449, zone = "Un'Goro Crater", x = 49, y = 45, note = "Find the hottest area of Fire Plume Ridge" }, -- 68
        { type = "TURNIN", quest = 974, questName = "Finding the Source", npc = 10302, npcName = "Krakle", map = 1449, zone = "Un'Goro Crater", x = 30.9, y = 50.4 }, -- 69
    } end,
})
