-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_HUMAN_13_ARATHI_HIGHLANDS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_HUMAN_13_ARATHI_HIGHLANDS",
    name = "13. Arathi Highlands 33-34 (Human)",
    version = 2,
    faction = "Alliance",
    race = { "Human" },
    minLevel = 33,
    maxLevel = 34,
    map = 1417,
    zone = "Arathi Highlands",
    next = "GEN_ALLIANCE_HUMAN_14_DUSTWALLOW_MARSH",
    author = "ForeverGuide route planner",
    notes = "Chapter 13 of the Human route: level 33 to 34, 37 steps, ~107 min of play in the model (34430 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1417, zone = "Arathi Highlands", x = 45.9, y = 46.0, radius = 60, note = "travel to Arathi Highlands (Arathi Highlands)" }, -- 1
        { type = "NOTE", map = 1417, zone = "Arathi Highlands", x = 45.9, y = 46.0, text = "set your hearthstone at the inn in Arathi Highlands (if there is one)" }, -- 2
        { type = "ACCEPT", quest = 681, questName = "Northfold Manor", npc = 2700, npcName = "Captain Nials", map = 1417, zone = "Arathi Highlands", x = 45.8, y = 47.6 }, -- 3
        { type = "ACCEPT", quest = 8260, questName = "Arathor Basic Care Package", npc = 15127, npcName = "Samuel Hawke", map = 1417, zone = "Arathi Highlands", x = 46, y = 45.2 }, -- 4
        { type = "ACCEPT", quest = 8167, questName = "The Battle for Arathi Basin!", npc = 14983, npcName = "Field Marshal Oslight", map = 1417, zone = "Arathi Highlands", x = 45.8, y = 45.5 }, -- 5
        { type = "ACCEPT", quest = 691, questName = "Worth Its Weight in Gold", npc = 2788, npcName = "Apprentice Kryten", map = 1417, zone = "Arathi Highlands", x = 46.2, y = 47.8 }, -- 6
        { type = "TURNIN", quest = 8167, questName = "The Battle for Arathi Basin!", npc = 14983, npcName = "Field Marshal Oslight", map = 1417, zone = "Arathi Highlands", x = 45.8, y = 45.5 }, -- 7
        { type = "TURNIN", quest = 8260, questName = "Arathor Basic Care Package", npc = 15127, npcName = "Samuel Hawke", map = 1417, zone = "Arathi Highlands", x = 46, y = 45.2 }, -- 8
        { type = "KILL", quest = 681, questName = "Northfold Manor", npc = 2586, target = "Syndicate Highwayman / Syndicate Mercenary", count = 10, map = 1417, zone = "Arathi Highlands", x = 33.9, y = 32.9, near = true }, -- 9
        { type = "COLLECT", quest = 691, questName = "Worth Its Weight in Gold", target = "Witherbark Tusk", count = 10, map = 1417, zone = "Arathi Highlands", x = 34.6, y = 39.5, near = true }, -- 10
        { type = "KILL", quest = 691, questName = "Worth Its Weight in Gold", npc = 2555, target = "Witherbark Witch Doctor", count = 10, map = 1417, zone = "Arathi Highlands", x = 32.6, y = 44.4, near = true, note = "loot Witherbark Medicine Pouch" }, -- 11
        { type = "KILL", quest = 691, questName = "Worth Its Weight in Gold", npc = 2557, target = "Witherbark Shadow Hunter", count = 4, map = 1417, zone = "Arathi Highlands", x = 66.3, y = 80.5, near = true, note = "loot Shadow Hunter Knife" }, -- 12
        { type = "TURNIN", quest = 681, questName = "Northfold Manor", npc = 2700, npcName = "Captain Nials", map = 1417, zone = "Arathi Highlands", x = 45.8, y = 47.6 }, -- 13
        { type = "ACCEPT", quest = 682, questName = "Stromgarde Badges", npc = 2700, npcName = "Captain Nials", map = 1417, zone = "Arathi Highlands", x = 45.8, y = 47.6 }, -- 14
        { type = "TURNIN", quest = 691, questName = "Worth Its Weight in Gold", npc = 2788, npcName = "Apprentice Kryten", map = 1417, zone = "Arathi Highlands", x = 46.2, y = 47.8 }, -- 15
        { type = "ACCEPT", quest = 693, questName = "Wand over Fist", npc = 2789, npcName = "Skuerto", map = 1417, zone = "Arathi Highlands", x = 46.7, y = 47 }, -- 16
        { type = "COLLECT", quest = 682, questName = "Stromgarde Badges", target = "Stromgarde Badge", count = 7, map = 1417, zone = "Arathi Highlands", x = 29.2, y = 61.3, near = true }, -- 17
        { type = "KILL", quest = 693, questName = "Wand over Fist", npc = 2793, target = "Kor'gresh Coldrage", map = 1417, zone = "Arathi Highlands", x = 54.8, y = 81.9, note = "loot Trelane's Wand of Invocation" }, -- 18
        { type = "TURNIN", quest = 682, questName = "Stromgarde Badges", npc = 2700, npcName = "Captain Nials", map = 1417, zone = "Arathi Highlands", x = 45.8, y = 47.6 }, -- 19
        { type = "TURNIN", quest = 693, questName = "Wand over Fist", npc = 2789, npcName = "Skuerto", map = 1417, zone = "Arathi Highlands", x = 46.7, y = 47 }, -- 20
        { type = "TURNIN", quest = 659, questName = "Hints of a New Plague?", npc = 2712, npcName = "Quae", map = 1417, zone = "Arathi Highlands", x = 60.2, y = 53.9 }, -- 21
        { type = "ACCEPT", quest = 658, questName = "Hints of a New Plague?", npc = 2712, npcName = "Quae", map = 1417, zone = "Arathi Highlands", x = 60.2, y = 53.9 }, -- 22
        { type = "COLLECT", quest = 658, questName = "Hints of a New Plague?", target = "Sealed Folder", map = 1417, zone = "Arathi Highlands", x = 52.5, y = 61.5, near = true }, -- 23
        { type = "TURNIN", quest = 658, questName = "Hints of a New Plague?", npc = 2712, npcName = "Quae", map = 1417, zone = "Arathi Highlands", x = 60.2, y = 53.9 }, -- 24
        { type = "ACCEPT", quest = 657, questName = "Hints of a New Plague?", npc = 2712, npcName = "Quae", map = 1417, zone = "Arathi Highlands", x = 60.2, y = 53.9 }, -- 25
        { type = "TURNIN", quest = 657, questName = "Hints of a New Plague?", npc = 2713, npcName = "Kinelory", map = 1417, zone = "Arathi Highlands", x = 60.2, y = 53.9 }, -- 26
        { type = "ACCEPT", quest = 660, questName = "Hints of a New Plague?", npc = 2713, npcName = "Kinelory", map = 1417, zone = "Arathi Highlands", x = 60.2, y = 53.9 }, -- 27
        { type = "COMPLETE", quest = 660, questName = "Hints of a New Plague?", target = "Protect Kinelory", map = 1417, zone = "Arathi Highlands", x = 60.1, y = 53.8, note = "Protect Kinelory" }, -- 28
        { type = "TURNIN", quest = 660, questName = "Hints of a New Plague?", npc = 2712, npcName = "Quae", map = 1417, zone = "Arathi Highlands", x = 60.2, y = 53.9 }, -- 29
        { type = "ACCEPT", quest = 642, questName = "The Princess Trapped", map = 1417, zone = "Arathi Highlands", x = 62.5, y = 33.7 }, -- 30
        { type = "COLLECT", quest = 642, questName = "The Princess Trapped", target = "Mote of Myzrael", count = 12, map = 1417, zone = "Arathi Highlands", x = 76.2, y = 42.5, near = true }, -- 31
        { type = "TURNIN", quest = 642, questName = "The Princess Trapped", map = 1417, zone = "Arathi Highlands", x = 84.3, y = 31 }, -- 32
        { type = "ACCEPT", quest = 651, questName = "Stones of Binding", map = 1417, zone = "Arathi Highlands", x = 84.3, y = 31 }, -- 33
        { type = "COLLECT", quest = 651, questName = "Stones of Binding", target = "Cresting Key", map = 1417, zone = "Arathi Highlands", x = 66.7, y = 29.7 }, -- 34
        { type = "COLLECT", quest = 651, questName = "Stones of Binding", target = "Thundering Key", map = 1417, zone = "Arathi Highlands", x = 52, y = 50.7 }, -- 35
        { type = "COLLECT", quest = 651, questName = "Stones of Binding", target = "Burning Key", map = 1417, zone = "Arathi Highlands", x = 25.5, y = 30.1 }, -- 36
        { type = "TURNIN", quest = 651, questName = "Stones of Binding", map = 1417, zone = "Arathi Highlands", x = 36.2, y = 57.4 }, -- 37
    },
})
