-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_DWARF_47_WINTERSPRING.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_DWARF_47_WINTERSPRING",
    name = "47. Winterspring 56-58 (Dwarf)",
    version = 2,
    faction = "Alliance",
    race = { "Dwarf", "Gnome" },
    minLevel = 56,
    maxLevel = 58,
    map = 1452,
    zone = "Winterspring",
    next = "GEN_ALLIANCE_DWARF_48_SILITHUS",
    author = "ForeverGuide route planner",
    notes = "Chapter 47 of the Dwarf route: level 56 to 58, 9 steps, ~549 min of play in the model (1981 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1451, zone = "Silithus", x = 50.1, y = 37.5, radius = 60, note = "use your hearthstone (Silithus)" }, -- 1
        { type = "TRAVEL", map = 1452, zone = "Winterspring", x = 61.5, y = 38.4, radius = 60, note = "travel to Winterspring (Winterspring)" }, -- 2
        { type = "ACCEPT", quest = 969, questName = "Luck Be With You", npc = 10307, npcName = "Witch Doctor Mau'ari", map = 1452, zone = "Winterspring", x = 61.9, y = 38.3 }, -- 3
        { type = "COLLECT", quest = 969, questName = "Luck Be With You", target = "Frostmaul Shards", count = 4, map = 1452, zone = "Winterspring", x = 58.7, y = 63.6, near = true }, -- 4
        { type = "TURNIN", quest = 969, questName = "Luck Be With You", npc = 10307, npcName = "Witch Doctor Mau'ari", map = 1452, zone = "Winterspring", x = 61.9, y = 38.3 }, -- 5
        { type = "ACCEPT", quest = 975, questName = "Cache of Mau'ari", npc = 10307, npcName = "Witch Doctor Mau'ari", map = 1452, zone = "Winterspring", x = 61.9, y = 38.3 }, -- 6
        { type = "TURNIN", quest = 975, questName = "Cache of Mau'ari", npc = 10307, npcName = "Witch Doctor Mau'ari", map = 1452, zone = "Winterspring", x = 61.9, y = 38.3 }, -- 7
        { type = "GRIND", npc = 7443, target = "Shardtooth Mauler", level = 57, map = 1452, zone = "Winterspring", x = 59.8, y = 41.3, near = true, note = "grind Shardtooth Mauler (level 54-56) to level 57 - nothing worth questing at 56" }, -- 8
        { type = "GRIND", npc = 7445, target = "Elder Shardtooth", level = 58, map = 1452, zone = "Winterspring", x = 61.5, y = 27.3, near = true, note = "grind Elder Shardtooth (level 57-58) to level 58 - nothing worth questing at 57" }, -- 9
    },
})
