-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_SEARING_GORGE.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_SEARING_GORGE",
    name = "Searing Gorge 43-50 (Alliance)",
    version = 1,
    faction = "Alliance",
    minLevel = 43,
    maxLevel = 50,
    next = "GEN_ALLIANCE_BLASTED_LANDS",
    author = "ForeverGuide route generator",
    notes = "Auto-generated from the quest database: 21 quests, 66 steps, model reaches level 45. Not a speedrun route - a sensible order; the engine adapts as you play.",
    steps = {
        { type = "ACCEPT", quest = 4449, questName = "Caught!", map = 1427, zone = "Searing Gorge", x = 65.6, y = 62.2 }, -- 1
        { type = "ACCEPT", quest = 3367, questName = "Suntara Stones", npc = 8284, npcName = "Dorius Stonetender", map = 1427, zone = "Searing Gorge", x = 63.9, y = 61 }, -- 2
        { type = "KILL", quest = 4449, questName = "Caught!", npc = 5839, target = "Dark Iron Geologist", map = 1427, zone = "Searing Gorge", x = 63.9, y = 60.4 }, -- 3
        { type = "COLLECT", quest = 4449, questName = "Caught!", target = "Silk Cloth", map = 1427, zone = "Searing Gorge", x = 48.9, y = 55.1 }, -- 4
        { type = "TURNIN", quest = 4449, questName = "Caught!", map = 1427, zone = "Searing Gorge", x = 65.6, y = 62.2 }, -- 5
        { type = "ACCEPT", quest = 3441, questName = "Divine Retribution", npc = 8479, npcName = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 6
        { type = "KILL", quest = 3441, questName = "Divine Retribution", npc = 8479, target = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 7
        { type = "TURNIN", quest = 3441, questName = "Divine Retribution", npc = 8479, npcName = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 8
        { type = "ACCEPT", quest = 3442, questName = "The Flawless Flame", npc = 8479, npcName = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 9
        { type = "COLLECT", quest = 3442, questName = "The Flawless Flame", target = "Heart of Flame / Golem Oil", map = 1427, zone = "Searing Gorge", x = 40.7, y = 36.7 }, -- 10
        { type = "TURNIN", quest = 3442, questName = "The Flawless Flame", npc = 8479, npcName = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 11
        { type = "ACCEPT", quest = 3443, questName = "Forging the Shaft", npc = 8479, npcName = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 12
        { type = "COLLECT", quest = 3443, questName = "Forging the Shaft", target = "Thorium Plated Dagger", map = 1427, zone = "Searing Gorge", x = 42.7, y = 36.4 }, -- 13
        { type = "TURNIN", quest = 3443, questName = "Forging the Shaft", npc = 8479, npcName = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 14
        { type = "ACCEPT", quest = 3452, questName = "The Flame's Casing", npc = 8479, npcName = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 15
        { type = "COLLECT", quest = 3452, questName = "The Flame's Casing", target = "Symbol of Ragnaros", map = 1427, zone = "Searing Gorge", x = 25.1, y = 37.2 }, -- 16
        { type = "TURNIN", quest = 3452, questName = "The Flame's Casing", npc = 8479, npcName = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 17
        { type = "ACCEPT", quest = 3453, questName = "The Torch of Retribution", npc = 8479, npcName = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 18
        { type = "KILL", quest = 3453, questName = "The Torch of Retribution", npc = 8479, target = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 19
        { type = "TURNIN", quest = 3453, questName = "The Torch of Retribution", npc = 8479, npcName = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 20
        { type = "ACCEPT", quest = 3454, questName = "The Torch of Retribution", npc = 8479, npcName = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 21
        { type = "TURNIN", quest = 3454, questName = "The Torch of Retribution", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39.1 }, -- 22
        { type = "ACCEPT", quest = 3462, questName = "Squire Maltrake", npc = 8479, npcName = "Kalaran Windblade", map = 1427, zone = "Searing Gorge", x = 39.1, y = 39 }, -- 23
        { type = "TURNIN", quest = 3462, questName = "Squire Maltrake", npc = 8509, npcName = "Squire Maltrake", map = 1427, zone = "Searing Gorge", x = 39.2, y = 39 }, -- 24
        { type = "ACCEPT", quest = 3463, questName = "Set Them Ablaze!", npc = 8509, npcName = "Squire Maltrake", map = 1427, zone = "Searing Gorge", x = 39.2, y = 39 }, -- 25
        { type = "COMPLETE", quest = 3463, questName = "Set Them Ablaze!", target = "Sentry Brazier", map = 1427, zone = "Searing Gorge", x = 33.3, y = 54.5, note = "Northern Tower Ablaze" }, -- 26
        { type = "COMPLETE", quest = 3463, questName = "Set Them Ablaze!", target = "Sentry Brazier", map = 1427, zone = "Searing Gorge", x = 35.7, y = 60.7, note = "Western Tower Ablaze" }, -- 27
        { type = "COMPLETE", quest = 3463, questName = "Set Them Ablaze!", target = "Sentry Brazier", map = 1427, zone = "Searing Gorge", x = 44, y = 60.9, note = "Southern Tower Ablaze" }, -- 28
        { type = "COMPLETE", quest = 3463, questName = "Set Them Ablaze!", target = "Sentry Brazier", map = 1427, zone = "Searing Gorge", x = 50.1, y = 54.7, note = "Eastern Tower Ablaze" }, -- 29
        { type = "TURNIN", quest = 3463, questName = "Set Them Ablaze!", npc = 8509, npcName = "Squire Maltrake", map = 1427, zone = "Searing Gorge", x = 39.2, y = 39 }, -- 30
        { type = "ACCEPT", quest = 3481, questName = "Trinkets...", map = 1427, zone = "Searing Gorge", x = 38.9, y = 39 }, -- 31
        { type = "TURNIN", quest = 3481, questName = "Trinkets...", map = 1427, zone = "Searing Gorge", x = 38.9, y = 39 }, -- 32
        { type = "ACCEPT", quest = 3377, questName = "Prayer to Elune", npc = 8436, npcName = "Zamael Lunthistle", map = 1427, zone = "Searing Gorge", x = 29.6, y = 26.3 }, -- 33
        { type = "KILL", quest = 3377, questName = "Prayer to Elune", npc = 8436, target = "Zamael Lunthistle", map = 1427, zone = "Searing Gorge", x = 29.6, y = 26.3 }, -- 34
        { type = "TURNIN", quest = 3377, questName = "Prayer to Elune", npc = 8436, npcName = "Zamael Lunthistle", map = 1427, zone = "Searing Gorge", x = 29.6, y = 26.3 }, -- 35
        { type = "ACCEPT", quest = 3378, questName = "Prayer to Elune", npc = 8436, npcName = "Zamael Lunthistle", map = 1427, zone = "Searing Gorge", x = 29.6, y = 26.3 }, -- 36
        { type = "COLLECT", quest = 3378, questName = "Prayer to Elune", target = "Prayer to Elune", map = 1427, zone = "Searing Gorge", x = 29.7, y = 25.9 }, -- 37
        { type = "COMPLETE", quest = 3367, questName = "Suntara Stones", target = "Dorius Escort", map = 1427, zone = "Searing Gorge", x = 74.5, y = 19.4, note = "Dorius Escort" }, -- 38
        { type = "TURNIN", quest = 3367, questName = "Suntara Stones", map = 1427, zone = "Searing Gorge", x = 74.5, y = 19.3 }, -- 39
        { type = "ACCEPT", quest = 3368, questName = "Suntara Stones", map = 1427, zone = "Searing Gorge", x = 74.5, y = 19.3 }, -- 40
        { type = "TURNIN", quest = 3378, questName = "Prayer to Elune", npc = 4090, npcName = "Astarii Starseeker", map = 1457, zone = "Darnassus", x = 38.3, y = 81 }, -- 41
        { type = "TURNIN", quest = 3368, questName = "Suntara Stones", npc = 8256, npcName = "Curator Thorius", map = 1455, zone = "Ironforge", x = 71.5, y = 15.7 }, -- 42
        { type = "GRIND", level = 45, note = "the next quests need level 45" }, -- 43
        { type = "ACCEPT", quest = 7701, questName = "WANTED: Overseer Maltorius", map = 1427, zone = "Searing Gorge", x = 37.7, y = 26.5 }, -- 44
        { type = "ACCEPT", quest = 7728, questName = "STOLEN: Smithing Tuyere and Lookout's Spyglass", map = 1427, zone = "Searing Gorge", x = 37.7, y = 26.5 }, -- 45
        { type = "ACCEPT", quest = 7729, questName = "JOB OPPORTUNITY: Culling the Competition", map = 1427, zone = "Searing Gorge", x = 37.7, y = 26.5 }, -- 46
        { type = "ACCEPT", quest = 7723, questName = "Curse These Fat Fingers", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 47
        { type = "ACCEPT", quest = 7724, questName = "Fiery Menace!", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 48
        { type = "ACCEPT", quest = 7727, questName = "Incendosaurs? Whateverosaur is More Like It", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 49
        { type = "ACCEPT", quest = 7722, questName = "What the Flux?", npc = 14624, npcName = "Master Smith Burninate", map = 1427, zone = "Searing Gorge", x = 38.8, y = 28.5 }, -- 50
        { type = "KILL", quest = 7729, questName = "JOB OPPORTUNITY: Culling the Competition", npc = 5846, target = "Dark Iron Taskmaster", map = 1427, zone = "Searing Gorge", x = 41.2, y = 23.3 }, -- 51
        { type = "KILL", quest = 7729, questName = "JOB OPPORTUNITY: Culling the Competition", npc = 5844, target = "Dark Iron Slaver", map = 1427, zone = "Searing Gorge", x = 43.3, y = 24 }, -- 52
        { type = "KILL", quest = 7727, questName = "Incendosaurs? Whateverosaur is More Like It", npc = 9318, target = "Incendosaur", map = 1427, zone = "Searing Gorge", x = 44.6, y = 24.9 }, -- 53
        { type = "COLLECT", quest = 7722, questName = "What the Flux?", target = "Secret Plans: Fiery Flux", map = 1427, zone = "Searing Gorge", x = 40.5, y = 35.7 }, -- 54
        { type = "KILL", quest = 7701, questName = "WANTED: Overseer Maltorius", npc = 14621, target = "Overseer Maltorius", map = 1427, zone = "Searing Gorge", x = 40.8, y = 35.9, note = "loot Head of Overseer Maltorius" }, -- 55
        { type = "KILL", quest = 7723, questName = "Curse These Fat Fingers", npc = 5854, target = "Heavy War Golem", map = 1427, zone = "Searing Gorge", x = 44.8, y = 38.7 }, -- 56
        { type = "KILL", quest = 7728, questName = "STOLEN: Smithing Tuyere and Lookout's Spyglass", npc = 5840, target = "Dark Iron Steamsmith", map = 1427, zone = "Searing Gorge", x = 40, y = 48.3, note = "loot Smithing Tuyere" }, -- 57
        { type = "KILL", quest = 7728, questName = "STOLEN: Smithing Tuyere and Lookout's Spyglass", npc = 8566, target = "Dark Iron Lookout", map = 1427, zone = "Searing Gorge", x = 33.7, y = 51.9, note = "loot Lookout's Spyglass" }, -- 58
        { type = "KILL", quest = 7724, questName = "Fiery Menace!", npc = 5858, target = "Greater Lava Spider", map = 1427, zone = "Searing Gorge", x = 28, y = 50.4 }, -- 59
        { type = "TURNIN", quest = 7722, questName = "What the Flux?", npc = 14624, npcName = "Master Smith Burninate", map = 1427, zone = "Searing Gorge", x = 38.8, y = 28.5 }, -- 60
        { type = "TURNIN", quest = 7723, questName = "Curse These Fat Fingers", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 61
        { type = "TURNIN", quest = 7724, questName = "Fiery Menace!", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 62
        { type = "TURNIN", quest = 7727, questName = "Incendosaurs? Whateverosaur is More Like It", npc = 14627, npcName = "Hansel Heavyhands", map = 1427, zone = "Searing Gorge", x = 38.6, y = 27.8 }, -- 63
        { type = "TURNIN", quest = 7728, questName = "STOLEN: Smithing Tuyere and Lookout's Spyglass", npc = 14626, npcName = "Taskmaster Scrange", map = 1427, zone = "Searing Gorge", x = 39, y = 27.5 }, -- 64
        { type = "TURNIN", quest = 7729, questName = "JOB OPPORTUNITY: Culling the Competition", npc = 14626, npcName = "Taskmaster Scrange", map = 1427, zone = "Searing Gorge", x = 39, y = 27.5 }, -- 65
        { type = "TURNIN", quest = 7701, questName = "WANTED: Overseer Maltorius", npc = 14634, npcName = "Lookout Captain Lolo Longstriker", map = 1427, zone = "Searing Gorge", x = 37.7, y = 26.6 }, -- 66
    },
})
