-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_TAUREN_32_BURNING_STEPPES.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_TAUREN_32_BURNING_STEPPES",
    name = "32. Burning Steppes 50-51 (Tauren)",
    version = 2,
    faction = "Horde",
    race = { "Tauren" },
    minLevel = 50,
    maxLevel = 51,
    map = 1428,
    zone = "Burning Steppes",
    next = "GEN_HORDE_TAUREN_33_THE_HINTERLANDS",
    author = "ForeverGuide route planner",
    notes = "Chapter 32 of the Tauren route: level 50 to 51, 8 steps, ~160 min of play in the model (39833 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "GRIND", npc = 7033, target = "Firegut Ogre", level = 51, map = 1428, zone = "Burning Steppes", x = 75.2, y = 45.3, near = true, note = "grind Firegut Ogre (level 50-51) to level 51 - nothing worth questing at 50" }, -- 1
        { type = "ACCEPT", quest = 4296, questName = "Tablet of the Seven", npc = 9536, npcName = "Maxwort Uberglint", map = 1428, zone = "Burning Steppes", x = 65.2, y = 23.9 }, -- 2
        { type = "ACCEPT", quest = 4726, questName = "Broodling Essence", npc = 10267, npcName = "Tinkee Steamboil", map = 1428, zone = "Burning Steppes", x = 65.2, y = 24 }, -- 3
        { type = "ACCEPT", quest = 4123, questName = "The Heart of the Mountain", npc = 9536, npcName = "Maxwort Uberglint", map = 1428, zone = "Burning Steppes", x = 65.2, y = 23.9 }, -- 4
        { type = "TURNIN", quest = 4123, questName = "The Heart of the Mountain", npc = 9536, npcName = "Maxwort Uberglint", map = 1428, zone = "Burning Steppes", x = 65.2, y = 23.9 }, -- 5
        { type = "TURNIN", quest = 4726, questName = "Broodling Essence", npc = 10267, npcName = "Tinkee Steamboil", map = 1428, zone = "Burning Steppes", x = 65.2, y = 24 }, -- 6
        { type = "COLLECT", quest = 4296, questName = "Tablet of the Seven", target = "Tablet Transcript", map = 1428, zone = "Burning Steppes", x = 54.1, y = 40.8 }, -- 7
        { type = "TURNIN", quest = 4296, questName = "Tablet of the Seven", npc = 9536, npcName = "Maxwort Uberglint", map = 1428, zone = "Burning Steppes", x = 65.2, y = 23.9 }, -- 8
    },
})
