-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_ALLIANCE_HUMAN_36_IRONFORGE.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_ALLIANCE_HUMAN_36_IRONFORGE",
    name = "36. Ironforge 50-50 (Human)",
    version = 2,
    faction = "Alliance",
    race = { "Human" },
    minLevel = 50,
    maxLevel = 50,
    map = 1455,
    zone = "Ironforge",
    next = "GEN_ALLIANCE_HUMAN_37_BURNING_STEPPES",
    author = "ForeverGuide route planner",
    notes = "Chapter 36 of the Human route: level 50 to 50, 9 steps, ~26 min of play in the model (68029 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1455, zone = "Ironforge", x = 60.5, y = 48.3, radius = 60, note = "travel to Ironforge (Ironforge)" }, -- 1
        { type = "ACCEPT", quest = 3702, questName = "The Smoldering Ruins of Thaurissan", npc = 8879, npcName = "Royal Historian Archesonus", map = 1455, zone = "Ironforge", x = 38.4, y = 55.3 }, -- 2
        { type = "ACCEPT", quest = 8371, questName = "Concerted Efforts", npc = 15351, npcName = "Alliance Brigadier General", map = 1455, zone = "Ironforge", x = 70.4, y = 91.1 }, -- 3
        { type = "ACCEPT", quest = 8375, questName = "Remember Alterac Valley!", npc = 15351, npcName = "Alliance Brigadier General", map = 1455, zone = "Ironforge", x = 70.4, y = 91.1 }, -- 4
        { type = "TURNIN", quest = 8371, questName = "Concerted Efforts", npc = 15351, npcName = "Alliance Brigadier General", map = 1455, zone = "Ironforge", x = 70.4, y = 91.1 }, -- 5
        { type = "TURNIN", quest = 8375, questName = "Remember Alterac Valley!", npc = 15351, npcName = "Alliance Brigadier General", map = 1455, zone = "Ironforge", x = 70.4, y = 91.1 }, -- 6
        { type = "KILL", quest = 3702, questName = "The Smoldering Ruins of Thaurissan", npc = 8879, target = "Royal Historian Archesonus", count = 1, map = 1455, zone = "Ironforge", x = 38.4, y = 55.3 }, -- 7
        { type = "TURNIN", quest = 3702, questName = "The Smoldering Ruins of Thaurissan", npc = 8879, npcName = "Royal Historian Archesonus", map = 1455, zone = "Ironforge", x = 38.4, y = 55.3 }, -- 8
        { type = "TURNIN", quest = 8484, questName = "The Brokering of Peace", npc = 2784, npcName = "King Magni Bronzebeard", map = 1455, zone = "Ironforge", x = 39.1, y = 56.2 }, -- 9
    },
})
