-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_SKYBORNE_15_DUSTWALLOW_MARSH.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_SKYBORNE_15_DUSTWALLOW_MARSH",
    name = "15. Dustwallow Marsh 42-42 (Skyborne)",
    version = 2,
    faction = "Horde",
    race = { "Skyborne" },
    minLevel = 42,
    maxLevel = 42,
    map = 1445,
    zone = "Dustwallow Marsh",
    next = "GEN_HORDE_SKYBORNE_16_ORGRIMMAR",
    author = "ForeverGuide route planner",
    notes = "Chapter 15 of the Skyborne route: level 42 to 42, 23 steps, ~73 min of play in the model (38749 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1445, zone = "Dustwallow Marsh", x = 36.8, y = 32.1, radius = 60, note = "travel to Dustwallow Marsh (Dustwallow Marsh)" }, -- 1
        { type = "ACCEPT", quest = 1166, questName = "Overlord Mok'Morokk's Concern", npc = 4500, npcName = "Overlord Mok'Morokk", map = 1445, zone = "Dustwallow Marsh", x = 36.3, y = 31.4 }, -- 2
        { type = "ACCEPT", quest = 1169, questName = "Identifying the Brood", npc = 4501, npcName = "Draz'Zilb", map = 1445, zone = "Dustwallow Marsh", x = 37.2, y = 33.1 }, -- 3
        { type = "ACCEPT", quest = 1168, questName = "Army of the Black Dragon", npc = 4502, npcName = "Tharg", map = 1445, zone = "Dustwallow Marsh", x = 37.4, y = 31.4 }, -- 4
        { type = "KILL", quest = 1168, questName = "Army of the Black Dragon", npc = 4329, target = "Firemane Scout", count = 10, map = 1445, zone = "Dustwallow Marsh", x = 39, y = 64.6, near = true }, -- 5
        { type = "COLLECT", quest = 1166, questName = "Overlord Mok'Morokk's Concern", target = "Mok'Morokk's Grog", map = 1445, zone = "Dustwallow Marsh", x = 38.7, y = 65.6 }, -- 6
        { type = "KILL", quest = 1168, questName = "Army of the Black Dragon", npc = 4331, target = "Firemane Ash Tail / Firemane Scalebane", count = 10, map = 1445, zone = "Dustwallow Marsh", x = 39.4, y = 66.6, near = true }, -- 7
        { type = "COLLECT", quest = 1166, questName = "Overlord Mok'Morokk's Concern", target = "Mok'Morokk's Strongbox", map = 1445, zone = "Dustwallow Marsh", x = 36.6, y = 69.6 }, -- 8
        { type = "COLLECT", quest = 1169, questName = "Identifying the Brood", target = "Searing Tongue / Searing Heart", count = 15, map = 1445, zone = "Dustwallow Marsh", x = 37.4, y = 74.2, near = true }, -- 9
        { type = "COLLECT", quest = 1166, questName = "Overlord Mok'Morokk's Concern", target = "Mok'Morokk's Snuff", map = 1445, zone = "Dustwallow Marsh", x = 44.5, y = 66 }, -- 10
        { type = "TURNIN", quest = 1169, questName = "Identifying the Brood", npc = 4501, npcName = "Draz'Zilb", map = 1445, zone = "Dustwallow Marsh", x = 37.2, y = 33.1 }, -- 11
        { type = "ACCEPT", quest = 1170, questName = "The Brood of Onyxia", npc = 4501, npcName = "Draz'Zilb", map = 1445, zone = "Dustwallow Marsh", x = 37.2, y = 33.1 }, -- 12
        { type = "TURNIN", quest = 1168, questName = "Army of the Black Dragon", npc = 4502, npcName = "Tharg", map = 1445, zone = "Dustwallow Marsh", x = 37.4, y = 31.4 }, -- 13
        { type = "TURNIN", quest = 1166, questName = "Overlord Mok'Morokk's Concern", npc = 4500, npcName = "Overlord Mok'Morokk", map = 1445, zone = "Dustwallow Marsh", x = 36.3, y = 31.4 }, -- 14
        { type = "TURNIN", quest = 1170, questName = "The Brood of Onyxia", npc = 4500, npcName = "Overlord Mok'Morokk", map = 1445, zone = "Dustwallow Marsh", x = 36.3, y = 31.4 }, -- 15
        { type = "ACCEPT", quest = 1171, questName = "The Brood of Onyxia", npc = 4500, npcName = "Overlord Mok'Morokk", map = 1445, zone = "Dustwallow Marsh", x = 36.3, y = 31.4 }, -- 16
        { type = "TURNIN", quest = 1171, questName = "The Brood of Onyxia", npc = 4501, npcName = "Draz'Zilb", map = 1445, zone = "Dustwallow Marsh", x = 37.2, y = 33.1 }, -- 17
        { type = "ACCEPT", quest = 1172, questName = "The Brood of Onyxia", npc = 4501, npcName = "Draz'Zilb", map = 1445, zone = "Dustwallow Marsh", x = 37.2, y = 33.1 }, -- 18
        { type = "COMPLETE", quest = 1172, questName = "The Brood of Onyxia", target = "Egg of Onyxia", count = 5, map = 1445, zone = "Dustwallow Marsh", x = 48.5, y = 73.6, near = true, note = "Egg of Onyxia destroyed" }, -- 19
        { type = "TURNIN", quest = 1172, questName = "The Brood of Onyxia", npc = 4501, npcName = "Draz'Zilb", map = 1445, zone = "Dustwallow Marsh", x = 37.2, y = 33.1 }, -- 20
        { type = "ACCEPT", quest = 1173, questName = "Challenge Overlord Mok'Morokk", npc = 4500, npcName = "Overlord Mok'Morokk", map = 1445, zone = "Dustwallow Marsh", x = 36.3, y = 31.4 }, -- 21
        { type = "COMPLETE", quest = 1173, questName = "Challenge Overlord Mok'Morokk", target = "Drive Overlord Mok'Morokk from Brackenwall Village", map = 1445, zone = "Dustwallow Marsh", x = 36.4, y = 31.4, note = "Drive Overlord Mok'Morokk from Brackenwall Village" }, -- 22
        { type = "TURNIN", quest = 1173, questName = "Challenge Overlord Mok'Morokk", npc = 4501, npcName = "Draz'Zilb", map = 1445, zone = "Dustwallow Marsh", x = 37.2, y = 33.1 }, -- 23
    },
})
