-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_TAUREN_43_WINTERSPRING.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_TAUREN_43_WINTERSPRING",
    name = "43. Winterspring 56-56 (Tauren)",
    version = 2,
    faction = "Horde",
    race = { "Tauren" },
    minLevel = 56,
    maxLevel = 56,
    map = 1452,
    zone = "Winterspring",
    next = "GEN_HORDE_TAUREN_44_FELWOOD",
    author = "ForeverGuide route planner",
    notes = "Chapter 43 of the Tauren route: level 56 to 56, 27 steps, ~90 min of play in the model (44792 xp/h). Route tuned for xp per hour: low-value quests and long escorts are skipped on purpose; group (elite) quests appear as optional steps (1 here).",
    stepCount = 27,
    steps = function() return {
        { type = "TRAVEL", map = 1451, zone = "Silithus", x = 50.1, y = 37.6, radius = 60, note = "use your hearthstone (Silithus)" }, -- 1
        { type = "TRAVEL", map = 1452, zone = "Winterspring", x = 61.4, y = 38.2, radius = 60, note = "travel to Winterspring (Winterspring)" }, -- 2
        { type = "NOTE", map = 1452, zone = "Winterspring", x = 61.4, y = 38.2, text = "set your hearthstone at the inn in Winterspring (if there is one)" }, -- 3
        { type = "ACCEPT", quest = 3783, questName = "Are We There, Yeti?", npc = 10305, npcName = "Umi Rumplesnicker", map = 1452, zone = "Winterspring", x = 60.9, y = 37.6 }, -- 4
        { type = "ACCEPT", quest = 969, questName = "Luck Be With You", npc = 10307, npcName = "Witch Doctor Mau'ari", map = 1452, zone = "Winterspring", x = 61.9, y = 38.3 }, -- 5
        { type = "ACCEPT", quest = 5054, questName = "Ursius of the Shardtooth", npc = 10303, npcName = "Storm Shadowhoof", map = 1452, zone = "Winterspring", x = 61.9, y = 38.4, optional = true, note = "group quest (elite mobs) - optional, take it only with company" }, -- 6
        { type = "KILL", quest = 5054, questName = "Ursius of the Shardtooth", npc = 10806, target = "Ursius", count = 1, map = 1452, zone = "Winterspring", x = 64, y = 24.1, optional = true }, -- 7
        { type = "TURNIN", quest = 5054, questName = "Ursius of the Shardtooth", npc = 10303, npcName = "Storm Shadowhoof", map = 1452, zone = "Winterspring", x = 61.9, y = 38.4, optional = true }, -- 8
        { type = "COLLECT", quest = 3783, questName = "Are We There, Yeti?", target = "Thick Yeti Fur", count = 10, map = 1452, zone = "Winterspring", x = 58.8, y = 34, near = true }, -- 9
        { type = "TURNIN", quest = 3783, questName = "Are We There, Yeti?", npc = 10305, npcName = "Umi Rumplesnicker", map = 1452, zone = "Winterspring", x = 60.9, y = 37.6 }, -- 10
        { type = "ACCEPT", quest = 977, questName = "Are We There, Yeti?", npc = 10305, npcName = "Umi Rumplesnicker", map = 1452, zone = "Winterspring", x = 60.9, y = 37.6 }, -- 11
        { type = "COLLECT", quest = 977, questName = "Are We There, Yeti?", target = "Pristine Yeti Horn", count = 2, map = 1452, zone = "Winterspring", x = 64.7, y = 40.6, near = true }, -- 12
        { type = "COLLECT", quest = 969, questName = "Luck Be With You", target = "Frostmaul Shards", count = 4, map = 1452, zone = "Winterspring", x = 58.7, y = 63.6, near = true }, -- 13
        { type = "TURNIN", quest = 977, questName = "Are We There, Yeti?", npc = 10305, npcName = "Umi Rumplesnicker", map = 1452, zone = "Winterspring", x = 60.9, y = 37.6 }, -- 14
        { type = "TURNIN", quest = 969, questName = "Luck Be With You", npc = 10307, npcName = "Witch Doctor Mau'ari", map = 1452, zone = "Winterspring", x = 61.9, y = 38.3 }, -- 15
        { type = "ACCEPT", quest = 975, questName = "Cache of Mau'ari", npc = 10307, npcName = "Witch Doctor Mau'ari", map = 1452, zone = "Winterspring", x = 61.9, y = 38.3 }, -- 16
        { type = "TURNIN", quest = 975, questName = "Cache of Mau'ari", npc = 10307, npcName = "Witch Doctor Mau'ari", map = 1452, zone = "Winterspring", x = 61.9, y = 38.3 }, -- 17
        { type = "TURNIN", quest = 3908, questName = "It's a Secret to Everybody", npc = 9298, npcName = "Donova Snowden", map = 1452, zone = "Winterspring", x = 31.3, y = 45.2 }, -- 18
        { type = "ACCEPT", quest = 5082, questName = "Threat of the Winterfall", npc = 9298, npcName = "Donova Snowden", map = 1452, zone = "Winterspring", x = 31.3, y = 45.2 }, -- 19
        { type = "KILL", quest = 5082, questName = "Threat of the Winterfall", npc = 7442, target = "Winterfall Pathfinder / Winterfall Totemic", count = 8, map = 1452, zone = "Winterspring", x = 33.4, y = 37.7, near = true }, -- 20
        { type = "KILL", quest = 5082, questName = "Threat of the Winterfall", npc = 7440, target = "Winterfall Den Watcher", count = 8, map = 1452, zone = "Winterspring", x = 30.5, y = 36.9, near = true }, -- 21
        { type = "ACCEPT", quest = 8464, questName = "Winterfall Activity", npc = 11556, npcName = "Salfa", map = 1452, zone = "Winterspring", x = 27.7, y = 34.5 }, -- 22
        { type = "KILL", quest = 8464, questName = "Winterfall Activity", npc = 7440, target = "Winterfall Den Watcher", count = 8, map = 1452, zone = "Winterspring", x = 30.3, y = 36.3, near = true }, -- 23
        { type = "TURNIN", quest = 5082, questName = "Threat of the Winterfall", npc = 9298, npcName = "Donova Snowden", map = 1452, zone = "Winterspring", x = 31.3, y = 45.2 }, -- 24
        { type = "KILL", quest = 8464, questName = "Winterfall Activity", npc = 7438, target = "Winterfall Ursa", count = 8, map = 1452, zone = "Winterspring", x = 65.1, y = 37.2, near = true }, -- 25
        { type = "KILL", quest = 8464, questName = "Winterfall Activity", npc = 7439, target = "Winterfall Shaman", count = 8, map = 1452, zone = "Winterspring", x = 67.4, y = 35.2, near = true }, -- 26
        { type = "TURNIN", quest = 8464, questName = "Winterfall Activity", npc = 11556, npcName = "Salfa", map = 1452, zone = "Winterspring", x = 27.7, y = 34.5 }, -- 27
    } end,
})
