-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_TAUREN_17_ORGRIMMAR.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_TAUREN_17_ORGRIMMAR",
    name = "17. Orgrimmar 42-42 (Tauren)",
    version = 2,
    faction = "Horde",
    race = { "Tauren" },
    minLevel = 42,
    maxLevel = 42,
    map = 1454,
    zone = "Orgrimmar",
    next = "GEN_HORDE_TAUREN_18_BADLANDS",
    author = "ForeverGuide route planner",
    notes = "Chapter 17 of the Tauren route: level 42 to 42, 8 steps, ~17 min of play in the model (52107 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1454, zone = "Orgrimmar", x = 60.2, y = 40.1, radius = 60, note = "travel to Orgrimmar (Orgrimmar)" }, -- 1
        { type = "NOTE", map = 1454, zone = "Orgrimmar", x = 60.2, y = 40.1, text = "set your hearthstone at the inn in Orgrimmar (if there is one)" }, -- 2
        { type = "ACCEPT", quest = 649, questName = "Ripple Recovery", npc = 6986, npcName = "Dran Droffers", map = 1454, zone = "Orgrimmar", x = 59.5, y = 36.6 }, -- 3
        { type = "TURNIN", quest = 649, questName = "Ripple Recovery", npc = 6987, npcName = "Malton Droffers", map = 1454, zone = "Orgrimmar", x = 59.7, y = 36.9 }, -- 4
        { type = "TURNIN", quest = 32, questName = "Rise of the Silithid", npc = 7010, npcName = "Zilzibin Drumlore", map = 1454, zone = "Orgrimmar", x = 56.3, y = 46.7 }, -- 5
        { type = "TURNIN", quest = 7732, questName = "Zukk'ash Report", npc = 7010, npcName = "Zilzibin Drumlore", map = 1454, zone = "Orgrimmar", x = 56.3, y = 46.7 }, -- 6
        { type = "TURNIN", quest = 2976, questName = "A Grim Discovery", npc = 4485, npcName = "Belgrom Rockmaul", map = 1454, zone = "Orgrimmar", x = 75.2, y = 34.2 }, -- 7
        { type = "ACCEPT", quest = 650, questName = "Ripple Recovery", npc = 6987, npcName = "Malton Droffers", map = 1454, zone = "Orgrimmar", x = 59.7, y = 36.9 }, -- 8
    },
})
