-- AUTO-GENERATED by tools/compile_guides.py from guides-src/GEN_HORDE_ORC_12_FERALAS.json - DO NOT EDIT
local _, ns = ...
ns.RegisterGuide({
    id = "GEN_HORDE_ORC_12_FERALAS",
    name = "12. Feralas 39-40 (Orc)",
    version = 2,
    faction = "Horde",
    race = { "Orc", "Troll" },
    minLevel = 39,
    maxLevel = 40,
    map = 1444,
    zone = "Feralas",
    next = "GEN_HORDE_ORC_13_TANARIS",
    author = "ForeverGuide route planner",
    notes = "Chapter 12 of the Orc route: level 39 to 40, 43 steps, ~200 min of play in the model (34427 xp/h). Route tuned for xp per hour: low-value quests, elites and long escorts are skipped on purpose.",
    steps = {
        { type = "TRAVEL", map = 1444, zone = "Feralas", x = 75.0, y = 43.2, radius = 60, note = "travel to Feralas (Feralas)" }, -- 1
        { type = "NOTE", map = 1444, zone = "Feralas", x = 75.0, y = 43.2, text = "set your hearthstone at the inn in Feralas (if there is one)" }, -- 2
        { type = "ACCEPT", quest = 2862, questName = "War on the Woodpaw", npc = 7875, npcName = "Hadoken Swiftstrider", map = 1444, zone = "Feralas", x = 74.9, y = 42.5 }, -- 3
        { type = "ACCEPT", quest = 2975, questName = "The Ogres of Feralas", npc = 7777, npcName = "Rok Orhan", map = 1444, zone = "Feralas", x = 75.8, y = 43.6 }, -- 4
        { type = "ACCEPT", quest = 2987, questName = "Gordunni Cobalt", npc = 8021, npcName = "Orwin Gizzmick", map = 1444, zone = "Feralas", x = 75.7, y = 44.3 }, -- 5
        { type = "ACCEPT", quest = 2973, questName = "A New Cloak's Sheen", npc = 4544, npcName = "Krueg Skullsplitter", map = 1444, zone = "Feralas", x = 75.9, y = 42.7 }, -- 6
        { type = "COLLECT", quest = 2973, questName = "A New Cloak's Sheen", target = "Iridescent Sprite Darter Wing", count = 10, map = 1444, zone = "Feralas", x = 70.2, y = 46.6, near = true }, -- 7
        { type = "COLLECT", quest = 2862, questName = "War on the Woodpaw", target = "Woodpaw Gnoll Mane", count = 10, map = 1444, zone = "Feralas", x = 69.4, y = 50.8, near = true }, -- 8
        { type = "KILL", quest = 2975, questName = "The Ogres of Feralas", npc = 5237, target = "Gordunni Ogre Mage / Gordunni Ogre / Gordunni Brute", count = 10, map = 1444, zone = "Feralas", x = 76.1, y = 35, near = true }, -- 9
        { type = "COLLECT", quest = 2987, questName = "Gordunni Cobalt", target = "Gordunni Cobalt", count = 12, map = 1444, zone = "Feralas", x = 76.4, y = 33.1, near = true }, -- 10
        { type = "TURNIN", quest = 2973, questName = "A New Cloak's Sheen", npc = 4544, npcName = "Krueg Skullsplitter", map = 1444, zone = "Feralas", x = 75.9, y = 42.7 }, -- 11
        { type = "ACCEPT", quest = 2974, questName = "A Grim Discovery", npc = 4544, npcName = "Krueg Skullsplitter", map = 1444, zone = "Feralas", x = 75.9, y = 42.7 }, -- 12
        { type = "TURNIN", quest = 2975, questName = "The Ogres of Feralas", npc = 7777, npcName = "Rok Orhan", map = 1444, zone = "Feralas", x = 75.8, y = 43.6 }, -- 13
        { type = "TURNIN", quest = 2862, questName = "War on the Woodpaw", npc = 7875, npcName = "Hadoken Swiftstrider", map = 1444, zone = "Feralas", x = 74.9, y = 42.5 }, -- 14
        { type = "TURNIN", quest = 2987, questName = "Gordunni Cobalt", npc = 8021, npcName = "Orwin Gizzmick", map = 1444, zone = "Feralas", x = 75.7, y = 44.3 }, -- 15
        { type = "ACCEPT", quest = 2863, questName = "Alpha Strike", npc = 7875, npcName = "Hadoken Swiftstrider", map = 1444, zone = "Feralas", x = 74.9, y = 42.5 }, -- 16
        { type = "ACCEPT", quest = 2980, questName = "The Ogres of Feralas", npc = 7777, npcName = "Rok Orhan", map = 1444, zone = "Feralas", x = 75.8, y = 43.6 }, -- 17
        { type = "COLLECT", quest = 2974, questName = "A Grim Discovery", target = "Grimtotem Horn", count = 20, map = 1444, zone = "Feralas", x = 69.9, y = 40, near = true }, -- 18
        { type = "KILL", quest = 2863, questName = "Alpha Strike", npc = 5258, target = "Woodpaw Alpha", count = 5, map = 1444, zone = "Feralas", x = 66.1, y = 51.6, near = true }, -- 19
        { type = "KILL", quest = 2980, questName = "The Ogres of Feralas", npc = 5234, target = "Gordunni Mauler / Gordunni Warlock", count = 10, map = 1444, zone = "Feralas", x = 61.8, y = 54.5, near = true }, -- 20
        { type = "KILL", quest = 2980, questName = "The Ogres of Feralas", npc = 5236, target = "Gordunni Shaman", count = 10, map = 1444, zone = "Feralas", x = 60.4, y = 64.8, near = true }, -- 21
        { type = "ACCEPT", quest = 3121, questName = "A Strange Request", npc = 8115, npcName = "Witch Doctor Uzer'i", map = 1444, zone = "Feralas", x = 74.4, y = 43.4 }, -- 22
        { type = "ACCEPT", quest = 2822, questName = "The Mark of Quality", npc = 7854, npcName = "Jangdor Swiftstrider", map = 1444, zone = "Feralas", x = 74.4, y = 42.9 }, -- 23
        { type = "TURNIN", quest = 2863, questName = "Alpha Strike", npc = 7875, npcName = "Hadoken Swiftstrider", map = 1444, zone = "Feralas", x = 74.9, y = 42.5 }, -- 24
        { type = "TURNIN", quest = 2980, questName = "The Ogres of Feralas", npc = 7777, npcName = "Rok Orhan", map = 1444, zone = "Feralas", x = 75.8, y = 43.6 }, -- 25
        { type = "TURNIN", quest = 2974, questName = "A Grim Discovery", npc = 4544, npcName = "Krueg Skullsplitter", map = 1444, zone = "Feralas", x = 75.9, y = 42.7 }, -- 26
        { type = "ACCEPT", quest = 2902, questName = "Woodpaw Investigation", npc = 7875, npcName = "Hadoken Swiftstrider", map = 1444, zone = "Feralas", x = 74.9, y = 42.5 }, -- 27
        { type = "ACCEPT", quest = 2976, questName = "A Grim Discovery", npc = 4544, npcName = "Krueg Skullsplitter", map = 1444, zone = "Feralas", x = 75.9, y = 42.7 }, -- 28
        { type = "COLLECT", quest = 2822, questName = "The Mark of Quality", target = "Thick Yeti Hide", count = 10, map = 1444, zone = "Feralas", x = 56.5, y = 56.5, near = true }, -- 29
        { type = "TURNIN", quest = 2822, questName = "The Mark of Quality", npc = 7854, npcName = "Jangdor Swiftstrider", map = 1444, zone = "Feralas", x = 74.4, y = 42.9 }, -- 30
        { type = "ACCEPT", quest = 7734, questName = "Improved Quality", npc = 7854, npcName = "Jangdor Swiftstrider", map = 1444, zone = "Feralas", x = 74.4, y = 42.9 }, -- 31
        { type = "COLLECT", quest = 7734, questName = "Improved Quality", target = "Rage Scar Yeti Hide", count = 10, map = 1444, zone = "Feralas", x = 55.7, y = 33.1, near = true }, -- 32
        { type = "TURNIN", quest = 7734, questName = "Improved Quality", npc = 7854, npcName = "Jangdor Swiftstrider", map = 1444, zone = "Feralas", x = 74.4, y = 42.9 }, -- 33
        { type = "TURNIN", quest = 2902, questName = "Woodpaw Investigation", map = 1444, zone = "Feralas", x = 71.6, y = 55.9 }, -- 34
        { type = "ACCEPT", quest = 2903, questName = "The Battle Plans", map = 1444, zone = "Feralas", x = 71.6, y = 55.9 }, -- 35
        { type = "TURNIN", quest = 2903, questName = "The Battle Plans", npc = 7875, npcName = "Hadoken Swiftstrider", map = 1444, zone = "Feralas", x = 74.9, y = 42.5 }, -- 36
        { type = "ACCEPT", quest = 7730, questName = "Zukk'ash Infestation", npc = 7875, npcName = "Hadoken Swiftstrider", map = 1444, zone = "Feralas", x = 74.9, y = 42.5 }, -- 37
        { type = "ACCEPT", quest = 7731, questName = "Stinglasher", npc = 7875, npcName = "Hadoken Swiftstrider", map = 1444, zone = "Feralas", x = 74.9, y = 42.5 }, -- 38
        { type = "COLLECT", quest = 7730, questName = "Zukk'ash Infestation", target = "Zukk'ash Carapace", count = 20, map = 1444, zone = "Feralas", x = 76.2, y = 59.3, near = true }, -- 39
        { type = "KILL", quest = 7731, questName = "Stinglasher", npc = 14661, target = "Stinglasher", map = 1444, zone = "Feralas", x = 75.6, y = 60.9, note = "loot Stinglasher's Glands" }, -- 40
        { type = "TURNIN", quest = 7730, questName = "Zukk'ash Infestation", npc = 7875, npcName = "Hadoken Swiftstrider", map = 1444, zone = "Feralas", x = 74.9, y = 42.5 }, -- 41
        { type = "TURNIN", quest = 7731, questName = "Stinglasher", npc = 7875, npcName = "Hadoken Swiftstrider", map = 1444, zone = "Feralas", x = 74.9, y = 42.5 }, -- 42
        { type = "ACCEPT", quest = 7732, questName = "Zukk'ash Report", npc = 7875, npcName = "Hadoken Swiftstrider", map = 1444, zone = "Feralas", x = 74.9, y = 42.5 }, -- 43
    },
})
